### ISSUE TITLE
Exploit failed: NoMethodError undefined method `smtp_send_recv' for #<Module:exploit/unix/smtp/exim4_string_format

### ISSUE THREAD

**Issue by MattandMello** [rapid7/metasploit-framework#17411]
1
I was trying to run an exploit using Metasploit's Exim tool. In the process I will have used the exim4_string_format module. I gave as information a RHOST, LHOSTS AND LPORT. To attack the reverse_perl payload. As a consequence this error happened:
```python
[*] Started reverse TCP handler on 192.168.56.2:443 
[*] 192.168.56.5:25 - Connecting to 192.168.56.5:25 ...
[*] 192.168.56.5:25 - Server: 220 localhost ESMTP Exim 4.68 Thu, 22 Dec 2022 23:01:22 +0000
[-] 192.168.56.5:25 - Exploit failed: NoMethodError undefined method `smtp_send_recv' for #<Module:exploit/unix/smtp/exim4_string_format datastore=[{"WORKSPACE"=>nil, "VERBOSE"=>false, "WfsDelay"=>2, "EnableContextEncoding"=>false, "ContextInformationFile"=>nil, "DisablePayloadHandler"=>false, "RHOSTS"=>"192.168.56.5", "RPORT"=>25, "SSL"=>false, "SSLServerNameIndication"=>nil, "SSLVersion"=>"Auto", "SSLVerifyMode"=>"PEER", "SSLCipher"=>nil, "Proxies"=>nil, "CPORT"=>nil, "CHOST"=>nil, "ConnectTimeout"=>10, "TCP::max_send_size"=>0, "TCP::send_delay"=>0, "MAILFROM"=>"root@localhost", "MAILTO"=>"postmaster@localhost", "EHLO_NAME"=>nil, "SourceAddress"=>nil, "SkipEscalation"=>false, "SkipVersionCheck"=>false, "PAYLOAD"=>"cmd/unix/reverse_perl", "LHOST"=>"192.168.56.2", "LPORT"=>443, "UNPARSED_RHOSTS"=>"192.168.56.5", "RHOSTNAME"=>nil, "ReverseListenerBindPort"=>nil, "ReverseAllowProxy"=>false, "ReverseListenerComm"=>nil, "ReverseListenerBindAddress"=>nil, "ReverseListenerThreaded"=>false, "StagerRetryCount"=>10, "StagerRetryWait"=>5, "CreateSession"=>true, "InitialAutoRunScript"=>nil, "AutoRunScript"=>nil, "CommandShellCleanupCommand"=>nil, "AutoVerifySession"=>true, "TARGET"=>0}]>
[*] Exploit completed, but no session was created.
````
How am i supposed to fix it for my exploit to be successful?

**Comment by adfoster-r7** [comment]
Most likely broken by https://github.com/rapid7/metasploit-framework/pull/16153

Specifically these code changes:
https://github.com/rapid7/metasploit-framework/pull/16153/files#diff-8e0d331d91ab51b07accc6a7e8e5fd5259051ecf3ff54f7d4ee92c0714fcdf2e

I think as a work around, you should be able to modify `modules/exploits/unix/smtp/exim4_string_format.rb` to use the old `raw_send_recv ` method instead of `smtp_send_recv `

**Comment by MattandMello** [comment]
Sory but I am new at this field so if I understand well, when I chose my exim module, I have to change manually smtp to raw?
Like:
````
use exploit/unix/raw/exim4_string_format
 ````
