### ISSUE TITLE
NoMethodError - undefined method `api_unauthenticated_path' when initialising db

### ISSUE THREAD

**Issue by LucasAnderson07** [rapid7/metasploit-framework#14496]
## Steps to reproduce

1. Install metasploit-framework on Kubuntu 20.04.1 (not a virtual environment)
2. run `msfconsole`
3. Error appears when attempting to create a MSF web service user API token and also every time `msfdb reinit` is run.

I didn't notice that this was happening at first, but I started looking for errors after trying repeatedly to add a custom module and not having it show up when attempting to reload the modules. It seems like this error could be the cause but I don't know enough to be sure.

## Were you following a specific guide/tutorial or reading documentation?

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

## Expected behavior

Web Service should successfully initialise.

## Current behavior

console output after running `msfconsole`:

```
me@my_computer:~$ msfconsole

 ** Welcome to Metasploit Framework Initial Setup **
    Please answer a few questions to get started.


Would you like to use and setup a new database (recommended)? yes
====================================================================
Running the 'init' command for the database:
Creating database at /home/<username>/.msf4/db
Starting database at /home/<username>/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/<username>/.msf4/db/pg_hba.conf
Stopping database at /home/<username>/.msf4/db
Starting database at /home/<username>/.msf4/db...success
Creating initial database schema
====================================================================

====================================================================
Running the 'init' command for the webservice:
[?] Initial MSF web service account username? [<username>]: 
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...success
MSF web service started and online
Creating MSF web service user <username>

    ############################################################
    ##              MSF Web Service Credentials               ##
    ##                                                        ##
    ##        Please store these credentials securely.        ##
    ##    You will need them to connect to the webservice.    ##
    ############################################################

MSF web service username: <username>
MSF web service password: <password>
[!] Error creating MSF web service user API token
Failed to complete MSF web service configuration, please reinitialize.
Stopping MSF web service PID 16997
====================================================================


 ** Metasploit Framework Initial Setup Complete **

                                                  

 ______________________________________________________________________________
|                                                                              |
|                          3Kom SuperHack II Logon                             |
|______________________________________________________________________________|
|                                                                              |
|                                                                              |
|                                                                              |
|                 User Name:          [   security    ]                        |
|                                                                              |
|                 Password:           [               ]                        |
|                                                                              |
|                                                                              |
|                                                                              |
|                                   [ OK ]                                     |
|______________________________________________________________________________|
|                                                                              |
|                                                       https://metasploit.com |
|______________________________________________________________________________|


       =[ metasploit v6.0.21-dev-                         ]
+ -- --=[ 2083 exploits - 1126 auxiliary - 354 post       ]
+ -- --=[ 596 payloads - 45 encoders - 10 nops            ]
+ -- --=[ 7 evasion                                       ]

Metasploit tip: Use sessions -1 to interact with the 
last opened session

msf6 > db_status
[*] Connected to msf. Connection type: postgresql.
msf6 > 
```

`msf-ws.log` shows the error mentioned in the title. Running `msfdb reinit` afterwards outputs the same console messages and the exact same messages in `msf-ws.log`. Exact logs shown below.

### Metasploit version

Framework: 6.0.21-dev-
Console  : 6.0.21-dev-

## Additional Information
`debug` command output:

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
The local config file is empty, no global variables are set, and there is no active module.
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
7      debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
No matching patterns were found in framework.log.
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
No matching patterns were found in msf-ws.log.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[12/10/2020 13:04:31] [d(0)] core: Created user based module store
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred (logs show same issue happening twice - once for the first `msfconsole` command, and once for the following `msfdb reinit`):
<details>
<summary>Collapse</summary>

```
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.4/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/associations.rb:1855: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:260: warning: The called method `transaction' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:171: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:97: warning: The called method `initialize' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:132: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:25: warning: The called method `initialize' is defined here
2020-12-10 13:10:41 - NoMethodError - undefined method `api_unauthenticated_path' for #<Msf::WebServices::MetasploitApiApp:0x00007f2c192fc6b8>:
        /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/servlet/auth_servlet.rb:82:in `block in post_generate_token'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:87:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
        /opt/metasploit-framework/embedded/bin/thin:23:in `load'
        /opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
2020-12-10 13:10:43 -0500 Exiting!
2020-12-10 13:14:25 -0500 Writing PID to /home/<username>/.msf4/msf-ws.pid
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
2020-12-10 13:14:27 -0500 Thin web server (v1.8.0 codename Possessed Pickle)
2020-12-10 13:14:27 -0500 Maximum connections set to 1024
2020-12-10 13:14:27 -0500 Listening on localhost:5443, CTRL+C to stop
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.4/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.4/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/postgresql/oid/specialized_string.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.4/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/associations.rb:1855: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/associations.rb:1368: warning: The called method `has_many' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:260: warning: The called method `transaction' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:171: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:97: warning: The called method `initialize' is defined here
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:132: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/relation.rb:25: warning: The called method `initialize' is defined here
2020-12-10 13:14:32 - NoMethodError - undefined method `api_unauthenticated_path' for #<Msf::WebServices::MetasploitApiApp:0x00007f769f895f68>:
        /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/servlet/auth_servlet.rb:82:in `block in post_generate_token'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:87:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
        /opt/metasploit-framework/embedded/bin/thin:23:in `load'
        /opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
2020-12-10 13:14:34 -0500 Exiting!
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

Framework: 6.0.21-dev-
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Omnibus Installer

</details>

**Comment by adfoster-r7** [comment]
cc @dwelch-r7 - I haven't verified this yet, but it looks like zeitwerk to me? 👀

**Comment by adfoster-r7** [comment]
Thanks for the error report, this should be fixed in the next release of Metasploit
https://github.com/rapid7/metasploit-framework/pull/14499
