### PR TITLE
Updated calls to describe method to fix crashes

### PR DESCRIPTION
**Pull request by jra89**
Fixes for errors below (#14990 ):

```
Auxiliary failed: NoMethodError undefined method `ntp_private' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `ntp_control' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `describe' for Rex::Proto::NTP:Module
```

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `fuzzers/ntp/ntp_protocol_fuzzer`
- [ ] set RHOSTS 127.0.0.1
- [ ] **Verify** that whole run is finished without above-mentioned errors

### CODE REVIEW

**Comment by bcoles** [comment]
I tested these changes on a host which doesn't have a NTP server listening. It appears to have resolved the crash.

The Rex documentation shows that `ntp_control`, `ntp_private`, and `ntp_describe` are in fact properties of `Rex::Proto::NTP::Modes`.

https://www.rubydoc.info/github/rapid7/metasploit-framework/Rex/Proto/NTP/Modes

**Comment by adfoster-r7** [comment]
Thanks for raising an issue and a fix! :+1:

@dwelch-r7 Looks this might've been caused by https://github.com/rapid7/metasploit-framework/pull/14696 - potentially there's other code that needs updated too? 🔍

**Comment by dwelch-r7** [comment]
# Release Notes

Updates the NTP protocol fuzzer module to fix a crash
