### ISSUE TITLE
dns_bruteforce -- Auxiliary failed: NoMethodError undefined method `header' for nil:NilClass

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#5816]
MY Lab environment:
  - **OS**: Arch Linux x64
  - **Framework**: 4.11.4-dev-3688ae68
  - **Console**  : 4.11.4-dev-3688ae68.15168

Dns bruteforce is very common during information gathering. When I try to brute force google.com, something goes wrong. 

```
msf auxiliary(dns_bruteforce) > show options 

Module options (auxiliary/gather/dns_bruteforce):

   Name      Current Setting                                        Required  Description
   ----      ---------------                                        --------  -----------
   DOMAIN    google.com                                             yes       The target domain name
   NS        8.8.8.8                                                no        Specify the name server to use for queries, otherwise use the system DNS
   WORDLIST  /opt/metasploit-framework/data/wordlists/namelist.txt  yes       Wordlist file for domain name brute force.

msf auxiliary(dns_bruteforce) > run

[*] Enumerating google.com
[*] This Domain has wild-cards enabled!!
[!] Wild-card IP for 9713.google.com is: 212.232.132.94
[*] Using DNS server: 8.8.8.8
[*] Performing bruteforce against google.com
[*] Testing 0.google.com
W, [2015-08-09T15:02:00.047298 #7643]  WARN -- : Nameserver 8.8.8.8 not responding within UDP timeout, trying next one
F, [2015-08-09T15:02:00.047542 #7643] FATAL -- : No response from nameservers list: aborting
[-] Auxiliary failed: NoMethodError undefined method `header' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/lib/net/dns/resolver.rb:842:in `search'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_bruteforce.rb:66:in `get_ip'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_bruteforce.rb:115:in `block (2 levels) in dnsbrt'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

**Comment by all3g** [comment]
[**auxiliary/gather/dns_info**] and [**auxiliary/gather/dns_bruteforce**] have the same problem.

```
msf auxiliary(dns_info) > run

[*] Enumerating google.com
[*] This Domain has Wild-cards Enabled!!
[*] Wild-card IP for 9076.google.com is: 124.232.132.94
[*] Using DNS server: 8.8.8.8
[+] google.com - Address 216.58.221.78 found. Record type: A
[+] google.com - Address 2404:6800:4005:80b::200e found. Record type: AAAA
W, [2015-08-09T15:51:25.296838 #7643]  WARN -- : Nameserver 8.8.8.8 not responding within UDP timeout, trying next one
F, [2015-08-09T15:51:25.297099 #7643] FATAL -- : No response from nameservers list: aborting
[+] google.com - Name server ns1.google.com (216.239.32.10) found. Record type: NS
[+] google.com - Name server ns4.google.com (216.239.38.10) found. Record type: NS
[+] google.com - Name server ns2.google.com (216.239.34.10) found. Record type: NS
[+] google.com - Name server ns3.google.com (216.239.36.10) found. Record type: NS
W, [2015-08-09T15:51:30.820774 #7643]  WARN -- : Nameserver 8.8.8.8 not responding within UDP timeout, trying next one
F, [2015-08-09T15:51:30.820993 #7643] FATAL -- : No response from nameservers list: aborting
[-] Auxiliary failed: NoMethodError undefined method `header' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/lib/net/dns/resolver.rb:842:in `search'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_info.rb:122:in `get_ip'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_info.rb:175:in `block in get_soa'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_info.rb:167:in `each'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_info.rb:167:in `get_soa'
[-]   /opt/metasploit-framework/modules/auxiliary/gather/dns_info.rb:71:in `run'
[*] Auxiliary module execution completed

```

**Comment by all3g** [comment]
Debug Information as follow:

```
[3] pry(#<Net::DNS::Resolver>)> exit
W, [2015-08-10T07:37:54.370478 #4722]  WARN -- : Nameserver 8.8.8.8 not responding within UDP timeout, trying next one
F, [2015-08-10T07:37:54.370766 #4722] FATAL -- : No response from nameservers list: aborting

From: /opt/metasploit-framework/lib/net/dns/resolver.rb @ line 843 Net::DNS::Resolver#search:

    837: def search(name,type=Net::DNS::A,cls=Net::DNS::IN)
    838: 
    839:   # If the name contains at least one dot then try it as is first.
    840:   if name.include? "."
    841:     @logger.debug "Search(#{name},#{Net::DNS::RR::Types.new(type)},#{Net::DNS::RR::Classes.new(cls)})"
    842:     ans = query(name,type,cls)
 => 843:     binding.pry
    844:     return ans if ans.header.anCount > 0
    845:   end
    846: 
    847:   # If the name doesn't end in a dot then apply the search list.
    848:   if name !~ /\.$/ and @config[:dns_search]
    849:     @config[:searchlist].each do |domain|
    850:       newname = name + "." + domain
    851:       @logger.debug "Search(#{newname},#{Net::DNS::RR::Types.new(type)},#{Net::DNS::RR::Classes.new(cls)})"
    852:       ans = query(newname,type,cls)
    853:       return ans if ans.header.anCount > 0
    854:     end
    855:   end
    856: 
    857:   # Finally, if the name has no dots then try it as is.
    858:   @logger.debug "Search(#{name},#{Net::DNS::RR::Types.new(type)},#{Net::DNS::RR::Classes.new(cls)})"
    859:   query(name+".",type,cls)
    860: 
    861: end

[1] pry(#<Net::DNS::Resolver>)> ans
=> nil
[2] pry(#<Net::DNS::Resolver>)> name
=> "02.google.com"
[3] pry(#<Net::DNS::Resolver>)> type
=> "AAAA"
```

**Comment by jvazquez-r7** [comment]
@all3g it works for me here:

```
msf auxiliary(dns_info) > run

[*] Enumerating google.com
[*] Using DNS server: 8.8.8.8
[+] google.com - Address 74.125.227.200 found. Record type: A
[+] google.com - Address 74.125.227.196 found. Record type: A
[+] google.com - Address 74.125.227.195 found. Record type: A
[+] google.com - Address 74.125.227.194 found. Record type: A
[+] google.com - Address 74.125.227.198 found. Record type: A
[+] google.com - Address 74.125.227.193 found. Record type: A
[+] google.com - Address 74.125.227.192 found. Record type: A
[+] google.com - Address 74.125.227.201 found. Record type: A
[+] google.com - Address 74.125.227.199 found. Record type: A
[+] google.com - Address 74.125.227.206 found. Record type: A
[+] google.com - Address 74.125.227.197 found. Record type: A
[+] google.com - Address 2607:f8b0:4000:805::1007 found. Record type: AAAA
[+] google.com - Name server ns3.google.com (216.239.36.10) found. Record type: NS
[+] google.com - Name server ns1.google.com (216.239.32.10) found. Record type: NS
[+] google.com - Name server ns2.google.com (216.239.34.10) found. Record type: NS
[+] google.com - Name server ns4.google.com (216.239.38.10) found. Record type: NS
[+] google.com - ns1.google.com (216.239.32.10) found. Record type: SOA
[+] google.com - Mail server alt2.aspmx.l.google.com (64.233.190.27) found. Record type: MX
[+] google.com - Mail server alt2.aspmx.l.google.com (2607:f8b0:400d:c08::1b) found. Record type: MX
[+] google.com - Mail server aspmx.l.google.com (74.125.30.26) found. Record type: MX
[+] google.com - Mail server aspmx.l.google.com (2607:f8b0:4003:c0b::1b) found. Record type: MX
[+] google.com - Mail server alt1.aspmx.l.google.com (64.233.177.27) found. Record type: MX
[+] google.com - Mail server alt1.aspmx.l.google.com (2607:f8b0:400d:c0a::1a) found. Record type: MX
[+] google.com - Mail server alt4.aspmx.l.google.com (64.233.186.27) found. Record type: MX
[+] google.com - Mail server alt4.aspmx.l.google.com (2a00:1450:4013:c00::1a) found. Record type: MX
[+] google.com - Mail server alt3.aspmx.l.google.com (74.125.141.27) found. Record type: MX
[+] google.com - Mail server alt3.aspmx.l.google.com (2607:f8b0:400c:c06::1a) found. Record type: MX
[+] google.com - Text info found: v=spf1 include:_spf.google.com ~all . Record type: TXT
[*] Auxiliary module execution completed
```

But I get your exception and callstack when I try to use an invalid NS:

```
msf auxiliary(dns_info) > set NS 8.8.8.1
NS => 8.8.8.1
msf auxiliary(dns_info) > run

[*] Enumerating google.com
[*] Using DNS server: 8.8.8.1
W, [2015-08-17T17:20:58.355821 #7946]  WARN -- : Nameserver 8.8.8.1 not responding within UDP timeout, trying next one
F, [2015-08-17T17:20:58.355910 #7946] FATAL -- : No response from nameservers list: aborting
[-] Auxiliary failed: NoMethodError undefined method `header' for nil:NilClass
[-] Call stack:
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/lib/net/dns/resolver.rb:842:in `search'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/modules/auxiliary/gather/dns_info.rb:122:in `get_ip'
[-]   /Users/jvazquez/Projects/Code/metasploit-framework/modules/auxiliary/gather/dns_info.rb:55:in `run'
[*] Auxiliary module execution completed
```

Maybe are you unable to reach 8.8.8.8 from the location you're running msfconsole and the dns modules :?

**Comment by jvazquez-r7** [comment]
I guess you're able to reach the NS because I see you're having some success on resolving things =) maybe connectivity isn't pretty good, and/or too many lag from the machin you're using to execute the modules and reach the resolver :?

**Comment by jvazquez-r7** [comment]
I definitely could handle the situation by being sure the calls to `query` don't raise an Exception... but I'm curious about how to reproduce your problem. I feel like at some moment connectivity with the resolver is lost at half scan... but I'm not sure... so asking for some extra feedback @all3g !

**Comment by all3g** [comment]
PLease connect to chinese network with vpn, and set nameserver 8.8.8.8.  Dns requests are often timeout.

**Comment by void-in** [comment]
@all3g This might be related with the government surveillance efforts. HTTPS sites can't be monitored by the governments so usually the DNS queries for those domains are either dropped or redirected to their own machines. If you set the DNS to that of Google's, the surveillance people won't be able to determine your destination. I believe they are dropping all the DNS traffic that is not getting resolved from their own DNS servers.

**Comment by jvazquez-r7** [comment]
@all3g I've done #5816 to mitigate the problem. I cannot test by connecting to a chinese network with vpn, but tried to work with test cases which raise similar problems. Would be helpful if you can try #5884 on your specific situation. Of course since looks like you are losing connectivity with the NS in use (8.8.8.8) the bruteforce attack won't finish correctly, but hopefully with the above PR you'll get a better output instead of exceptions. Thanks!

**Comment by jvazquez-r7** [comment]
btw, thanks again for your report!
