### PR TITLE
Linux Post check file exists before read

### LINKED ISSUE #8557: enum_users_history crash
```
[-] [2017.06.14-10:53:52] Post failed: NoMethodError undefined method `gsub' for nil:NilClass
[-] [2017.06.14-10:53:52] Call stack:
[-] [2017.06.14-10:53:52]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.19/lib/msf/core/post/linux/system.rb:92:in `get_sysinfo'
[-] [2017.06.14-10:53:52]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.19/modules/post/linux/gather/enum_users_history.rb:31:in `run'
```

### PR DESCRIPTION
**Pull request by h00die**
Fixes #8557 
This work was ENTIRELY done by @bcoles , I take NO credit for it.  Just PRing his changes since he's been super busy lately.
When exploiting a router via `ssh_login` or other similar module, the Post system will try to read the issues file, which wont exist on a router, and crash.
This is just like #9029 and #8987 

## Verification

- [x] Start `msfconsole`
- [x] pop a shell on a router type device
- [x] try any of the modules described as broken in #8557 (top or last posts shows them)
- [x] **Verify** crashes don't happen anymore (or at least in the same line of code)

### CODE REVIEW

**Comment by acammack-r7** [comment]
Release Notes
===========

Allow collecting system info for post modules on embedded Linux devices without `/etc/issue`
