### ISSUE TITLE
NoMethodError undefined method `[]' for nil:NilClass in post/windows/manage/migrate

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#8360]
Came across this by accident because I did not unset the `AutoRunScript` when switching to a simple shell.
Here is the error:
https://github.com/rapid7/metasploit-framework/blob/04f11b0bf7d79b79485bbbe04d86bc59cb3d956a/modules/post/windows/manage/migrate.rb#L34

This script is missing a check if it's run inside a meterpreter session.

```
[*] Session ID 3 (10.x.x.x:12345 -> 10.y.y.y:1447) processing AutoRunScript 'post/windows/manage/migrate'
[-] Post failed: NoMethodError undefined method `[]' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/manage/migrate.rb:34:in `run'
```

# Settings
```
msf exploit(handler) > options

Module options (exploit/multi/handler):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------


Payload options (windows/shell_reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     10.x.x.x         yes       The listen address
   LPORT     12345            yes       The listen port


Exploit target:

   Id  Name
   --  ----
   0   Wildcard Target
```

```
msf exploit(handler) > advanced

Module advanced options (exploit/multi/handler):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   ContextInformationFile                   no        The information file that contains context information
   DisablePayloadHandler   false            no        Disable the handler code for the selected payload
   EnableContextEncoding   false            no        Use transient context when encoding payloads
   ExitOnSession           false            no        Return from the exploit after a session has been created
   ListenerTimeout         0                no        The maximum number of seconds to wait for new sessions
   VERBOSE                 false            no        Enable detailed status messages
   WORKSPACE                                no        Specify the workspace for this module
   WfsDelay                0                no        Additional delay when waiting for a session


Payload advanced options (windows/shell_reverse_tcp):

   Name                        Current Setting              Required  Description
   ----                        ---------------              --------  -----------
   AutoRunScript               post/windows/manage/migrate  no        A script to run automatically on session creation.
   InitialAutoRunScript                                     no        An initial script to run on session creation (before AutoRunScript)
   PrependMigrate              false                        yes       Spawns and runs shellcode in new process
   PrependMigrateProc                                       no        Process to spawn and run shellcode in
   ReverseAllowProxy           false                        yes       Allow reverse tcp even with Proxies specified. Connect back will NOT go through proxy but directly to LHOST
   ReverseConnectRetries       5                            yes       The number of connection attempts to try before exiting the process
   ReverseListenerBindAddress                               no        The specific IP address to bind to on the local system
   ReverseListenerBindPort                                  no        The port to bind to on the local system if different from LPORT
   ReverseListenerComm                                      no        The specific communication channel to use for this listener
   ReverseListenerThreaded     false                        yes       Handle every connection in a new thread (experimental)
   VERBOSE                     false                        no        Enable detailed status messages
   WORKSPACE                                                no        Specify the workspace for this module
```

**Comment by wvu-r7** [comment]
Do you no longer get a warning that you're running the post module inside an incompatible (shell) session? I noticed the loss of the message some time ago and was wondering if it still exists.

**Comment by FireFart** [comment]
@wvu-r7 nope. To reproduce run the following command and connect via netcat in another terminal to the listener:
```
`./docker/bin/msfconsole-dev -q -x "use exploit/multi/handler; set payload windows/shell_reverse_tcp; set AutoRunScript post/windows/manage/migrate; set LHOST 172.19.0.3; run"
[*] Processing docker/msfconsole.rc for ERB directives.
[*] resource (docker/msfconsole.rc)> Ruby Code (210 bytes)
[*] Rebuilding the module cache in the background...
payload => windows/shell_reverse_tcp
AutoRunScript => post/windows/manage/migrate
LHOST => 172.19.0.3
[*] Started reverse TCP handler on 172.19.0.3:4444
[*] Starting the payload handler...
[*] Command shell session 1 opened (172.19.0.3:4444 -> 172.19.0.1:50446) at 2017-05-10 07:26:58 +0000
[*] Session ID 1 (172.19.0.3:4444 -> 172.19.0.1:50446) processing AutoRunScript 'post/windows/manage/migrate'
[-] Post failed: NoMethodError undefined method `[]' for nil:NilClass
[-] Call stack:
[-]   /usr/src/metasploit-framework/modules/post/windows/manage/migrate.rb:31:in `run'
```

**Comment by wvu-r7** [comment]
Sounds like a regression in #7737/#7888.

**Comment by wvu-r7** [comment]
IIRC, I looked into this before and found that `setup` wasn't being run.

**Comment by wvu-r7** [comment]
Also, post modules should really show session compatibility in `info`.

**Comment by FireFart** [comment]
Works now:
```
[*] Processing docker/msfconsole.rc for ERB directives.
[*] resource (docker/msfconsole.rc)> Ruby Code (236 bytes)
LHOST => 172.19.0.3
[*] Rebuilding the module cache in the background...
payload => windows/shell_reverse_tcp
AutoRunScript => post/windows/manage/migrate
LHOST => 172.19.0.3
[*] Exploit running as background job 0.

[*] Started reverse TCP handler on 172.19.0.3:4444 
msf exploit(handler) > [*] Command shell session 1 opened (172.19.0.3:4444 -> 172.19.0.1:50854) at 2017-10-12 19:47:36 +0200

msf exploit(handler) > [*] 172.19.0.1 - Command shell session 1 closed.  Reason: Died from EOFError
[*] Command shell session 2 opened (172.19.0.3:4444 -> 172.19.0.1:50860) at 2017-10-12 19:47:51 +0200
[*] 172.19.0.1 - Command shell session 2 closed.  Reason: Died from EOFError
Interrupt: use the 'exit' command to quit
```
