### ISSUE TITLE
undefined method size for several NTP modules using the DRDOS mixin

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#9592]
I receive an email about this as well as a posting at https://kb.help.rapid7.com/discuss/5a0c920ee329a2002a19b2bc:

```
msf5 auxiliary(scanner/ntp/ntp_unsettrap_dos) > run

[-] Auxiliary failed: NoMethodError undefined method `size' for #<Rex::Proto::NTP::NTPControl:0x00007feb01363370>
[-] Call stack:
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:45:in `map'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:45:in `block in prove_amplification'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:30:in `each'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:30:in `prove_amplification'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:62:in `block in scanner_postscan'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:51:in `each'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:51:in `scanner_postscan'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/udp_scanner.rb:100:in `run_batch'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:215:in `block in run'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

A quick test of the other NTP modules shows that `auxiliary/scanner/ntp/ntp_req_nonce_dos` and `auxiliary/scanner/ntp/ntp_readvar` are also similarly affected.

@wwebb-r7 this can be reproduced by scanning 10.4.17.0/24.

Looks to have been caused by #8185, though it isn't immediately clear why it only affects this module.  Other modules which are missing the `to_binary_s` call appear to work.  🤔
