### PR TITLE
update NTP drdos lib to use correct method on bindata objects

### LINKED ISSUE #9592: undefined method size for several NTP modules using the DRDOS mixin
I receive an email about this as well as a posting at https://kb.help.rapid7.com/discuss/5a0c920ee329a2002a19b2bc:

```
msf5 auxiliary(scanner/ntp/ntp_unsettrap_dos) > run

[-] Auxiliary failed: NoMethodError undefined method `size' for #<Rex::Proto::NTP::NTPControl:0x00007feb01363370>
[-] Call stack:
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:45:in `map'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:45:in `block in prove_amplification'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:30:in `each'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/drdos.rb:30:in `prove_amplification'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:62:in `block in scanner_postscan'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:51:in `each'
[-]   /Users/jhart/rapid7/metasploit-framework/modules/auxiliary/scanner/ntp/ntp_unsettrap_dos.rb:51:in `scanner_postscan'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/udp_scanner.rb:100:in `run_batch'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:215:in `block in run'
[-]   /Users/jhart/rapid7/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

A quick test of the other NTP modules shows that `auxiliary/scanner/ntp/ntp_req_nonce_dos` and `auxiliary/scanner/ntp/ntp_readvar` are also similarly affected.

@wwebb-r7 this can be reproduced by scanning 10.4.17.0/24.

Looks to have been caused by #8185, though it isn't immediately clear why it only affects this module.  Other modules which are missing the `to_binary_s` call appear to work.  🤔

### PR DESCRIPTION
**Pull request by busterb**
Fixes #9592, this corrects some missed ports to bindata methods.

## Verification

- [ ] Start `msfconsole`
- [ ] `use scanner/ntp/ntp_unsettrap_dos`
- [ ] Scan a vulnerable host
- [ ] **Verify** that the module runs without errors

```
[+] 1.2.3.4:123 - Vulnerable to R7-2014-12 NTP Mode 6 UNSETTRAP DRDoS: 2x packet amplification and a 2x, 12-byte bandwidth amplification
```

### CODE REVIEW

**Comment by busterb** [comment]
Oh, for the sake of Pete, the mocks use a string, which isn't a bindata blob. I'm not sure if this rspec is helping in the way we hoped it would, since it didn't actually find the bug either :)

**Comment by jhart-r7** [comment]
Perhaps the rspec should have been updated as part of #8185?

**Comment by jhart-r7** [comment]
I've submitted a PR against this PR to fix it, https://github.com/busterb/metasploit-framework/pull/14

**Comment by busterb** [comment]
Thank you @jhart-r7 , landed and rebased.

**Comment by jhart-r7** [comment]
I'm not sure why the Sanity Test Execution is failing.  I'm not even sure what it is doing, because the Details link just links to all PRs.  

Also, what is the protocol for getting this landed now given that @busterb's name is on the PR but the only effective code written has my name on it?  Am I still allowed to merge this?

**Comment by jmartin-r7** [comment]
Jenkins test this please.

**Comment by jhart-r7** [comment]
LGTM:

```
[+] a.b.c.d:123 - Vulnerable to R7-2014-12 NTP Mode 6 UNSETTRAP DRDoS: 2x packet amplification and a 2x, 12-byte bandwidth amplification
```

**Comment by tdoan-r7** [comment]
# Release Notes
The scanner/ntp/ntp_unsettrap_dos module now runs without errors.
