### ISSUE TITLE
Error When Running exploit/windows/smb/ms17_010_psexec After Running `unset SMBuser`

### ISSUE THREAD

**Issue by jbarnett-r7** [rapid7/metasploit-framework#10795]
## Steps to reproduce

1. `use windows/smb/ms17_010_psexec`
2. `unset SMBUser`
3. `unset SMBPass`
4. `run`

## Expected behavior

If the module is able to successfully connect to a share, then I would get a session. In my case I am still failing to login, but I should get a meaningful error message informing me as such.

For example, when running the module against an inaccessible share prior to the `unset` commands I get:

```
msf5 exploit(windows/smb/ms17_010_psexec) > run

[*] Started reverse TCP handler on 172.28.128.1:4444 
[-] 172.28.128.3:445 - Rex::Proto::SMB::Exceptions::LoginError: Login Failed: The server responded with error: STATUS_ACCESS_DENIED (Command=115 WordCount=0)
[*] Exploit completed, but no session was created.
```

## Current behavior

I get an error with a squelched stack trace (that I am unable to find in the logs):

```
msf5 exploit(windows/smb/ms17_010_psexec) > run

[*] Started reverse TCP handler on 172.28.128.1:4444 
[-] 172.28.128.3:445 - Rex::Proto::SMB::Exceptions::LoginError: Login Failed: undefined method `force_encoding' for nil:NilClass
[*] Exploit completed, but no session was created.
```

## System stuff

Testing against a base Windows 2012 R2 install with a share that has Read/Write permission to Everyone.

Using a dev checkout of framework on OSX 10.13.6

### Metasploit version

`e05ee281905d58bee9627177bcfa0b271f79906f (HEAD -> master, upstream/master) Weekly dependency update`

### I installed Metasploit with:
- [ ] Source install (`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`)

### OS

OSX 10.13.6

**Comment by alienk8** [comment]
Help somebody, please. I've gotten the same error above.

**Comment by adfoster-r7** [comment]
I believe I fixed this as part of the datastore rewrite / Kerberos release in metasploit 6.3
