### PR TITLE
Fix SMB version crash on smb1

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fix SMB version crash on SMB 1 introduced by https://github.com/rapid7/metasploit-framework/pull/21266

Before 🔴 

```
[*] [2026.06.12-02:32:08] 10.140.111.141:445 (SMB Version Detection) - Running module.
[*] [2026.06.12-02:32:08] [auxiliary/scanner/smb/smb_version] 10.140.111.141:445    - Force SMB1 since SMB fingerprint needs native_lm/native_os information
[-] [2026.06.12-02:32:08] [auxiliary/scanner/smb/smb_version] 10.140.111.141:445    - 10.140.111.141: NoMethodError undefined method `dispatcher' for an instance of Rex::Proto::SMB::Client
```

After 🟢 

```
[*] 10.140.113.233:445    - SMB Detected (versions: 1, 2) (preferred dialect: SMB 2.1) (signatures: optional) (uptime: 7w 3d 11h 8m 24s) (guid: {cbd0e727-e283-4589-b0ed-9c3291ab2318}) (authentication domain: VAGRANT-2008R2)
[+] 10.140.113.233:445    -   Host is running Windows 2008 R2  Standard  SP1  (build: 7601)
[*] 10.140.113.233:445    -   SMB signing is not required
[*] 10.140.113.233 - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_version) > 
```

### CODE REVIEW

**Review by dwelch-r7 — APPROVED** [review]

**Comment by dwelch-r7** [comment]
# Release Notes

Fixes a crash in the `smb_version` module when run against SMBv1 targets
