### PR TITLE
Fix type validation in the notes add operation

### PR DESCRIPTION
**Pull request by mkienow-r7**
Fix issue with type validation in the notes add operation that was introduced in #9873. This also makes variable nil checks explicit for better style.

Example error output:
```
msf5 > notes --add --note "note data" 127.0.0.1
[-] Error while running command notes: undefined method `first' for nil:NilClass

Call stack:
/home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1069:in `block in cmd_notes'
/Users/mkienow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/msfdev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:998:in `cmd_notes'
/home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/home/msfdev/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/home/msfdev/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/msfdev/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
```

## Verification

- [x] Start `msfconsole`
- [x] Create a note with the note option, but without any type option: `notes --add --note "note data" <address>`
- [x] **Verify**  the `notes` command outputs the error "Exactly one type is required"
- [x] Create a note with the note option, but with the type option specifying two or more types: `notes --add --note "note data" --type test1,test2 <address>`
- [x] **Verify**  the `notes` command outputs the error "Exactly one type is required"
- [x] Create a note with a type option but without a note option: `notes --add --type "note type" <address>`
- [x] **Verify**  the `notes` command outputs the error "Data required"
- [x] Create a note with the note option and the type option specifying a single type: `notes --add --note "note data" --type "note type" <address>`
- [x] **Verify**  the output of the `notes` shows the newly added note
- [x] Update the note without note or type options: `notes --update <address>`
- [x] **Verify**  the `notes` command outputs the error "Update requires data or type"
- [x] Update the note with the type option specifying two or more types: `notes --update --type test1,test2 <address>`
- [x] **Verify**  the `notes` command outputs the error "Exactly one type is required"
- [x] Update the note's data: `notes --update --note "data update" <address>`
- [x] **Verify**  the output of the `notes` command shows the note's updated data
- [x] Update the note's type: `notes --update --type "type update" <address>`
- [x] **Verify**  the output of the `notes` command shows the note's updated type
- [x] Update the note's data and type: `notes --update --note "data update 2" --type "type update 2" <address>`
- [x] **Verify**  the output of the `notes` command shows the note's updated data and type

### CODE REVIEW

**Comment by asoto-r7** [comment]
@mkienow-r7: Thanks for the gloriously easy verification steps!

**Comment by asoto-r7** [comment]
## Release Notes

The recently-revised `notes` command now includes improved validation of the type field.
