### PR TITLE
fix execute and kill cmd usage/help

### PR DESCRIPTION
**Pull request by timwr**
Fixes a minor bug with command usage introduced with https://github.com/rapid7/metasploit-framework/pull/8117

## Verification
Before:
```
meterpreter > kill
[-] Error running command kill: NameError undefined local variable or method `cmd_kill_help' for #<Rex::Post::Meterpreter::Ui::Console::CommandDispatcher::Stdapi::Sys:0x007fab8caba498>
Did you mean?  cmd_pkill_help
               cmd_kill
               cmd_pkill
               cmd_help
               cmd_ps_help
               cmd_shell
               cmd_help_help
meterpreter > execute
Usage: execute -f file [options]

Executes a command on the remote machine.

OPTIONS:

    -H        Create the process hidden from view.
    -a <opt>  The arguments to pass to the command.
    -c        Channelized I/O (required for interaction).
    -d <opt>  The 'dummy' executable to launch when using -m.
    -f <opt>  The executable command to run.
    -h        Help menu.
    -i        Interact with the process after creating it.
    -k        Execute process on the meterpreters current desktop
    -m        Execute from memory.
    -s <opt>  Execute process in a given session as the session user
    -t        Execute process with currently impersonated thread tokenmeterpreter >
```
After:
```
meterpreter > kill
Usage: kill [pid1 [pid2 [pid3 ...]]] [-s]
Terminate one or more processes.
     -s        Kills the pid associated with the current session.
meterpreter > execute
Usage: execute -f file [options]

Executes a command on the remote machine.

OPTIONS:

    -H        Create the process hidden from view.
    -a <opt>  The arguments to pass to the command.
    -c        Channelized I/O (required for interaction).
    -d <opt>  The 'dummy' executable to launch when using -m.
    -f <opt>  The executable command to run.
    -h        Help menu.
    -i        Interact with the process after creating it.
    -k        Execute process on the meterpreters current desktop
    -m        Execute from memory.
    -s <opt>  Execute process in a given session as the session user
    -t        Execute process with currently impersonated thread token
meterpreter >
```

### CODE REVIEW

**Comment by bwatters-r7** [comment]
## Old
```
msf exploit(handler) > use exploit/multi/handler 
msf exploit(handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf exploit(handler) > set lhost <MSF_IP>
lhost => <MSF_IP>
msf exploit(handler) > set lport 4567
lport => 4567
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
^C[-] Exploit failed: Interrupt 
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
[*] Sending stage (1189423 bytes) to <Win10x64_IP>
[*] Meterpreter session 1 opened (<MSF_IP>:4567 -> <Win10x64_IP>:50726) at 2017-03-22 08:48:57 -0500

meterpreter > kill
[-] Error running command kill: NameError undefined local variable or method `cmd_kill_help' for #<Rex::Post::Meterpreter::Ui::Console::CommandDispatcher::Stdapi::Sys:0x00000005a714f8>
Did you mean?  cmd_pkill_help
               cmd_kill
               cmd_pkill
               cmd_help
               cmd_ps_help
               cmd_shell
               cmd_help_help
meterpreter > exit

```
### New
```
msf exploit(handler) > run

[*] Started reverse TCP handler on <MSF_IP>:4567 
[*] Starting the payload handler...
[*] Sending stage (1189423 bytes) to <Win10x64_IP>
[*] Meterpreter session 1 opened (<MSF_IP>:4567 -> <Win10x64_IP>:50749) at 2017-03-22 08:54:53 -0500

meterpreter > kill
Usage: kill [pid1 [pid2 [pid3 ...]]] [-s]
Terminate one or more processes.
     -s        Kills the pid associated with the current session.
meterpreter > ps

Process List
============

 PID   PPID  Name                          Arch  Session  User                    Path
 ---   ----  ----                          ----  -------  ----                    ----
 0     0     [System Process]                                                     
 4     0     System                                                               
 76    636   svchost.exe                                                          
 88    748   backgroundTaskHost.exe        x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\backgroundTaskHost.exe
 308   4     smss.exe                                                             
 336   584   dwm.exe                                                              
 420   412   csrss.exe                                                            
 496   412   wininit.exe                                                          
 508   488   csrss.exe                                                            
 584   488   winlogon.exe                                                         
 636   496   services.exe                                                         
 644   496   lsass.exe                                                            
 748   636   svchost.exe                                                          
 812   636   svchost.exe                                                          
 864   924   wuauclt.exe                                                          
 924   636   svchost.exe                                                          
 932   636   svchost.exe                                                          
 1000  636   svchost.exe                                                          
 1064  1000  WUDFHost.exe                                                         
 1072  636   svchost.exe                                                          
 1148  636   svchost.exe                                                          
 1364  4056  explorer.exe                  x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\explorer.exe
 1456  636   vmacthlp.exe                                                         
 1484  636   svchost.exe                                                          
 1656  748   WmiPrvSE.exe                                                         
 1672  636   svchost.exe                                                          
 1752  748   TiWorker.exe                                                         
 1760  636   svchost.exe                                                          
 1812  636   sqlwriter.exe                                                        
 1840  636   svchost.exe                                                          
 1856  636   TrustedInstaller.exe                                                 
 1992  636   spoolsv.exe                                                          
 2052  636   FoxitConnectedPDFService.exe                                         
 2072  636   svchost.exe                                                          
 2080  636   vmtoolsd.exe                                                         
 2088  636   VGAuthService.exe                                                    
 2112  636   GoogleUpdate.exe                                                     
 2192  4     Memory Compression                                                   
 2596  636   msdtc.exe                                                            
 2628  1364  met_rev_tcp2.exe              x64   1        DESKTOP-SO4MCA3\tmoose  C:\Users\tmoose\Desktop\met_rev_tcp2.exe
 2756  636   SearchIndexer.exe                                                    
 2852  1364  notepad.exe                   x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\notepad.exe
 2860  636   dllhost.exe                                                          
 2880  6192  chrome.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 2960  636   VSSVC.exe                                                            
 3192  636   svchost.exe                                                          
 3624  748   dllhost.exe                   x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\dllhost.exe
 3708  924   sihost.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\sihost.exe
 3728  636   svchost.exe                   x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\svchost.exe
 3768  924   taskhostw.exe                 x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\taskhostw.exe
 3920  5844  OneDrive.exe                  x86   1        DESKTOP-SO4MCA3\tmoose  C:\Users\tmoose\AppData\Local\Microsoft\OneDrive\OneDrive.exe
 3980  748   RuntimeBroker.exe             x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\RuntimeBroker.exe
 4340  748   ShellExperienceHost.exe       x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe
 4416  748   SearchUI.exe                  x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
 5240  6192  chrome.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 5532  1364  vmtoolsd.exe                  x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files\VMware\VMware Tools\vmtoolsd.exe
 6192  1364  chrome.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 6220  748   ApplicationFrameHost.exe      x64   1        DESKTOP-SO4MCA3\tmoose  C:\Windows\System32\ApplicationFrameHost.exe
 6412  6192  chrome.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 6820  6192  chrome.exe                    x64   1        DESKTOP-SO4MCA3\tmoose  C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 6824  924   taskhostw.exe                 x64   1                                

meterpreter > kill 2852
Killing: 2852
meterpreter > 

```

**Comment by bwatters-r7** [comment]
# Release Notes
This PR fixes the behavior of the `kill` command in meterpreter that was broken by a feature addition recently.
