### PR TITLE
lock reline again until better support is solved

### PR DESCRIPTION
**Pull request by jmartin-tech**
Rollback reline as it still causes exceptions in Ruby 2.6 and 2.7

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole` with a valid bundle in Ruby 2.6 and 2.7

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Not sure if we might need to roll back the linked bundler version, can't seem to get this to work with RVM and a fresh install of Ruby 2.7.6. This could potentially just be an issue with my install though.

```
 ~/git/metasploit-framework │ land-pr16964:pr/16964 ?3  bundle install     ✔ │ 2.7.6 Ruby 
Traceback (most recent call last):
	2: from /usr/share/rvm/rubies/ruby-2.7.6/bin/bundle:30:in `<main>'
	1: from /usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/usr/share/rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /home/gwillcox/git/metasploit-framework/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
 ~/git/metasploit-framework │ land-pr16964:pr/16964 ?3  gem install bundler:2.1.4
ERROR:  Loading command: install (LoadError)
	cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
 ~/git/metasploit-framework │ land-pr16964:pr/16964 ?3  
```

**Review by adfoster-r7 — APPROVED** [review]
Looks good to me - works with Ruby 2.7.2 and freshly installed 2.7.6:

```
msf6 exploit(linux/http/microfocus_obr_cmd_injection) > irb -e 'puts RUBY_DESCRIPTION'
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin20]
```

I didn't test with Ruby 2.6, as we're moments away from that being removed from our support list

**Review by gwillcox-r7 — APPROVED** [review]
